
from extract.main import extract
from extract.yfin import categorize_interval_and_sort_data
from load.google_sheets import call_apps_script, upload_to_gsheets
from transform.main import transform
from load.main import load
import asyncio
from transform.threebp import threebp_main
from transform.transform_functions import save_to_html_and_open
from utilities import dict_to_dataframe, load_pickle_object, save_dataframe
from config import sectors, industries, industry_equities
import time
from extract.data import Data
import pandas as pd
import datetime
from datetime import timedelta
import pandas_market_calendars as mcal

# --------------------------------------------------------------------
sectors = [
	{ "sector_symbol": "$TTGD", "sector_name": "TSX Financials Capped Index" },
	{ "sector_symbol": "TTFS", "sector_name": "TSX Financials Capped Index" },
	{ "sector_symbol": "TTMT", "sector_name": "TSX Materials Capped Index" },
	{ "sector_symbol": "TTEN", "sector_name": "TSX Energy Capped Index" },
	{ "sector_symbol": "TTIN", "sector_name": "TSX Industrials Capped Index" },
	{
		"sector_symbol": "TTTK",
		"sector_name": "TSX Information Tech Capped Index"
	},
	{ "sector_symbol": "TTUT", "sector_name": "TSX Utilities Capped Index" },
	{
		"sector_symbol": "TTCS",
		"sector_name": "TSX Consumer Staples Capped Index"
	},
	{ "sector_symbol": "TTRE", "sector_name": "TSX Real Estate Capped Index" },
	{
		"sector_symbol": "TTTS",
		"sector_name": "TSX Communication Services Capped Index"
	},
	{
		"sector_symbol": "TTCD",
		"sector_name": "TSX Consumer Discretionary Capped Index"
	},
	{ "sector_symbol": "TTHC", "sector_name": "TSX Health Care Capped Index" }
]

industries = [
	{ "industry_symbol": "VBVB", "industry_name": "TSX Beverages - Brewers" },
	{ "industry_symbol": "VSEM", "industry_name": "TSX Semiconductors" },
	{ "industry_symbol": "VSEQ", "industry_name": "TSX Semiconductor Equipment" },
	{
		"industry_symbol": "VPHR",
		"industry_name": "TSX Pharmaceutical Retailers"
	},
	{ "industry_symbol": "VENT", "industry_name": "TSX Entertainment" },
	{ "industry_symbol": "VMTF", "industry_name": "TSX Metal Fabrication" },
	{ "industry_symbol": "VCOC", "industry_name": "TSX Coking Coal" },
	{ "industry_symbol": "VTOB", "industry_name": "TSX Tobacco" },
	{ "industry_symbol": "VDCS", "industry_name": "TSX Discount Stores" },
	{ "industry_symbol": "VFIE", "industry_name": "TSX Financial Exchanges" },
	{ "industry_symbol": "VISS", "industry_name": "TSX Insurance - Specialty" },
	{ "industry_symbol": "VRCA", "industry_name": "TSX Resorts & Casinos" },
	{ "industry_symbol": "VFDD", "industry_name": "TSX Food Distribution" },
	{ "industry_symbol": "VSOL", "industry_name": "TSX Solar" },
	{ "industry_symbol": "VSCH", "industry_name": "TSX Specialty Chemicals" },
	{
		"industry_symbol": "VITS",
		"industry_name": "TSX Information Technology Srvs"
	},
	{ "industry_symbol": "VDRE", "industry_name": "TSX Diagnostics & Research" },
	{ "industry_symbol": "VBSD", "industry_name": "TSX Beverages - Soft Drinks" },
	{ "industry_symbol": "VBRO", "industry_name": "TSX Broadcasting" },
	{
		"industry_symbol": "VOGR",
		"industry_name": "TSX Oil & Gas Refining & Mrkt"
	},
	{ "industry_symbol": "VSHC", "industry_name": "TSX Shell Companies" },
	{ "industry_symbol": "VBMT", "industry_name": "TSX Building Materials" },
	{ "industry_symbol": "VLOD", "industry_name": "TSX Lodging" },
	{ "industry_symbol": "VBIO", "industry_name": "TSX Biotechnology" },
	{ "industry_symbol": "VINF", "industry_name": "TSX Insurance - Life" },
	{ "industry_symbol": "VPUB", "industry_name": "TSX Publishing" },
	{
		"industry_symbol": "VIPC",
		"industry_name": "TSX Insurance - Property & Casu"
	},
	{ "industry_symbol": "VMBS", "industry_name": "TSX Business Services" },
	{ "industry_symbol": "VPKF", "industry_name": "TSX Packaged Foods" },
	{ "industry_symbol": "VAPS", "industry_name": "TSX Apparel Stores" },
	{
		"industry_symbol": "VUIP",
		"industry_name": "TSX Utilities Independent Power"
	},
	{ "industry_symbol": "VRES", "industry_name": "TSX Real Estate Services" },
	{ "industry_symbol": "VPPP", "industry_name": "TSX Paper & Paper Products" },
	{ "industry_symbol": "VBOT", "industry_name": "TSX Bottom 100 Stocks" },
	{ "industry_symbol": "VOGM", "industry_name": "TSX Oil & Gas Midstream" },
	{ "industry_symbol": "VCEQ", "industry_name": "TSX Communication Equipment" },
	{ "industry_symbol": "VCSV", "industry_name": "TSX Credit Services" },
	{
		"industry_symbol": "VURE",
		"industry_name": "TSX Utilities Regulated Electric"
	},
	{ "industry_symbol": "VSRE", "industry_name": "TSX Specialty Retail" },
	{ "industry_symbol": "VHCP", "industry_name": "TSX Health Care Plans" },
	{
		"industry_symbol": "VRLS",
		"industry_name": "TSX Rental & Leasing Services"
	},
	{
		"industry_symbol": "VREV",
		"industry_name": "TSX Real Estate - Development"
	},
	{ "industry_symbol": "VBAG", "industry_name": "TSX Banks - Global" },
	{ "industry_symbol": "VSAP", "industry_name": "TSX Software - Application" },
	{ "industry_symbol": "VAGI", "industry_name": "TSX Agricultural Inputs" },
	{ "industry_symbol": "VIND", "industry_name": "TSX Insurance - Diversified" },
	{ "industry_symbol": "VUDI", "industry_name": "TSX Utilities Diversified" },
	{ "industry_symbol": "VOGI", "industry_name": "TSX Oil & Gas Integrated" },
	{
		"industry_symbol": "VDMM",
		"industry_name": "TSX Drug Manufacturers - Major"
	},
	{ "industry_symbol": "VAIR", "industry_name": "TSX Airlines" },
	{ "industry_symbol": "VOGE", "industry_name": "TSX Oil & Gas E&P" },
	{
		"industry_symbol": "VLWP",
		"industry_name": "TSX Lumber & Wood Production"
	},
	{ "industry_symbol": "VASM", "industry_name": "TSX Asset Management" },
	{ "industry_symbol": "VCOF", "industry_name": "TSX Confectioners" },
	{ "industry_symbol": "VTSE", "industry_name": "TSX Telecom Services" },
	{ "industry_symbol": "VAMN", "industry_name": "TSX Auto Manufacturers" },
	{ "industry_symbol": "VFOA", "industry_name": "TSX Footwear & Accessories" },
	{ "industry_symbol": "VSTL", "industry_name": "TSX Steel" },
	{ "industry_symbol": "VOGD", "industry_name": "TSX Oil & Gas Drilling" },
	{ "industry_symbol": "VCOG", "industry_name": "TSX Conglomerates" },
	{ "industry_symbol": "VGOL", "industry_name": "TSX Gold" },
	{ "industry_symbol": "VAAD", "industry_name": "TSX Aerospace & Defense" },
	{
		"industry_symbol": "VTCS",
		"industry_name": "TSX Indices Consumer Staples"
	},
	{ "industry_symbol": "VFMP", "industry_name": "TSX Farm Products" },
	{ "industry_symbol": "VGST", "industry_name": "TSX Grocery Stores" },
	{ "industry_symbol": "VTHC", "industry_name": "TSX Indices Health Care" },
	{
		"industry_symbol": "VPTC",
		"industry_name": "TSX Pollution Treatment Controls"
	},
	{ "industry_symbol": "VECO", "industry_name": "TSX Electronic Components" },
	{ "industry_symbol": "VSPO", "industry_name": "TSX Shipping & Ports" },
	{ "industry_symbol": "VPKC", "industry_name": "TSX Packaging & Containers" },
	{ "industry_symbol": "VBRE", "industry_name": "TSX Banks - Regional" },
	{
		"industry_symbol": "VEEP",
		"industry_name": "TSX Electrical Equipment & Parts"
	},
	{
		"industry_symbol": "VTTS",
		"industry_name": "TSX Indices Telecom Services"
	},
	{ "industry_symbol": "VMRF", "industry_name": "TSX Mortgage Finance" },
	{ "industry_symbol": "VCOE", "industry_name": "TSX Consumer Electronics" },
	{ "industry_symbol": "VAUP", "industry_name": "TSX Auto Parts" },
	{ "industry_symbol": "VRIS", "industry_name": "TSX REIT - Specialty" },
	{ "industry_symbol": "VMDD", "industry_name": "TSX Medical Devices" },
	{ "industry_symbol": "VTRU", "industry_name": "TSX Trucking" },
	{
		"industry_symbol": "VBWD",
		"industry_name": "TSX Beverages - Wine & Distiller"
	},
	{ "industry_symbol": "VLEI", "industry_name": "TSX Leisure" },
	{ "industry_symbol": "VTEN", "industry_name": "TSX Indices Energy" },
	{
		"industry_symbol": "VISL",
		"industry_name": "TSX Integrated Shipping & Logis"
	},
	{
		"industry_symbol": "VIMM",
		"industry_name": "TSX Industrial Metals Minerals"
	},
	{ "industry_symbol": "VITR", "industry_name": "TSX Internet Retail" },
	{
		"industry_symbol": "VHIS",
		"industry_name": "TSX Health Information Services"
	},
	{ "industry_symbol": "VCHE", "industry_name": "TSX Chemicals" },
	{ "industry_symbol": "VTIN", "industry_name": "TSX Indices Industrials" },
	{ "industry_symbol": "VGAM", "industry_name": "TSX Gambling" },
	{ "industry_symbol": "VAPM", "industry_name": "TSX Apparel Manufacturing" },
	{ "industry_symbol": "VAAA", "industry_name": "TSX Advertising Agencies" },
	{ "industry_symbol": "VTUT", "industry_name": "TSX Indices Utilities" },
	{
		"industry_symbol": "VEGC",
		"industry_name": "TSX Engineering & Construction"
	},
	{ "industry_symbol": "VSIL", "industry_name": "TSX Silver" },
	{
		"industry_symbol": "VHPP",
		"industry_name": "TSX Household & Personal Product"
	},
	{ "industry_symbol": "VTRS", "industry_name": "TSX Travel Services" },
	{
		"industry_symbol": "VFCE",
		"industry_name": "TSX Farm & Construction Equipt"
	},
	{
		"industry_symbol": "VDMS",
		"industry_name": "TSX Drug Specialty & Generic"
	},
	{
		"industry_symbol": "VSIM",
		"industry_name": "TSX Specialty Industrial Machine"
	},
	{ "industry_symbol": "VRRT", "industry_name": "TSX REIT - Retail" },
	{ "industry_symbol": "VRRE", "industry_name": "TSX REIT - Residential" },
	{ "industry_symbol": "VTFS", "industry_name": "TSX Indices Financials" },
	{ "industry_symbol": "VCSY", "industry_name": "TSX Computer Systems" },
	{ "industry_symbol": "VTRE", "industry_name": "TSX Indices Real Estate" },
	{
		"industry_symbol": "VSTI",
		"industry_name": "TSX Scientific & Technical Instr"
	},
	{ "industry_symbol": "VRDV", "industry_name": "TSX REIT - Diversified" },
	{
		"industry_symbol": "VRHF",
		"industry_name": "TSX REIT - Healthcare Faciltes"
	},
	{ "industry_symbol": "VAAS", "industry_name": "TSX Airports & Air Services" },
	{ "industry_symbol": "VTXS", "industry_name": "TSX Indices 60 Index" },
	{ "industry_symbol": "VPSS", "industry_name": "TSX Personal Services" },
	{ "industry_symbol": "VICI", "industry_name": "TSX Internet Content & Info" },
	{
		"industry_symbol": "VSIN",
		"industry_name": "TSX Software - Infrastructure"
	},
	{
		"industry_symbol": "VSPS",
		"industry_name": "TSX Security & Protection Srvs"
	},
	{ "industry_symbol": "VRST", "industry_name": "TSX Restaurants" },
	{ "industry_symbol": "VURG", "industry_name": "TSX Utilities Regulated Gas" },
	{
		"industry_symbol": "VTCD",
		"industry_name": "TSX Indices Consumer Discret"
	},
	{ "industry_symbol": "VLUG", "industry_name": "TSX Luxury Goods" },
	{
		"industry_symbol": "VTTK",
		"industry_name": "TSX Indices Information Tech"
	},
	{ "industry_symbol": "VHIM", "industry_name": "TSX Home Improvement Stores" },
	{ "industry_symbol": "VTMA", "industry_name": "TSX Textile Manufacturing" },
	{ "industry_symbol": "VRIN", "industry_name": "TSX REIT - Industrial" },
	{
		"industry_symbol": "VOPM",
		"industry_name": "TSX Other Precious Metals & Mine"
	},
	{ "industry_symbol": "VIDD", "industry_name": "TSX Industrial Distribution" },
	{ "industry_symbol": "VROF", "industry_name": "TSX REIT - Office" },
	{ "industry_symbol": "VCPM", "industry_name": "TSX Capital Markets" },
	{ "industry_symbol": "VTCO", "industry_name": "TSX Thermal Coal" },
	{ "industry_symbol": "VURA", "industry_name": "TSX Uranium" },
	{ "industry_symbol": "VRVE", "industry_name": "TSX Recreational Vehicles" },
	{ "industry_symbol": "VUTR", "industry_name": "TSX Utilities - Renewable" },
	{
		"industry_symbol": "VOGS",
		"industry_name": "TSX Oil & Gas Equipment & Srvs"
	},
	{ "industry_symbol": "VTMT", "industry_name": "TSX Indices Materials" },
	{ "industry_symbol": "VMDC", "industry_name": "TSX Medical Care" },
	{
		"industry_symbol": "VRED",
		"industry_name": "TSX Real Estate - Diversified"
	},
	{ "industry_symbol": "VWMA", "industry_name": "TSX Waste Management" },
	{ "industry_symbol": "VCOP", "industry_name": "TSX Copper" },
	{
		"industry_symbol": "VBPE",
		"industry_name": "TSX Building Products & Equpment"
	},
	{ "industry_symbol": "VTOP", "industry_name": "TSX Top 100 Stocks" },
	{
		"industry_symbol": "VMIS",
		"industry_name": "TSX Medical Instruments & Suppls"
	},
	{
		"industry_symbol": "VATD",
		"industry_name": "TSX Auto & Truck Dealerships"
	},
	{ "industry_symbol": "VINR", "industry_name": "TSX Insurance - Reinsurance" },
	{
		"industry_symbol": "VHFF",
		"industry_name": "TSX Home Furnishings & Fixture"
	},
	{
		"industry_symbol": "VEGM",
		"industry_name": "TSX Electronic Gaming & Media"
	}
]

industry_equities = [
        {
          "equity_symbol": "TECK-A.TO",
          "revLastQ": "N/A",
          "revGrowthLastQ": "unch",
          "revGrowth1qAgo": "unch",
          "revGrowth2qAgo": "unch",
          "grossProfitLastQ": "N/A",
          "operatingIncomeLastQ": "N/A",
          "netIncomeLastQ": "N/A",
          "revLastY": "N/A",
          "revGrowthLastY": "unch",
          "revGrowth1yAgo": "unch",
          "revGrowth2yAgo": "unch",
          "grossProfitLastY": "N/A",
          "operatingIncomeLastY": "N/A",
          "industry_symbol": "VIMM"
        },
        {
          "equity_symbol": "ACRG-B-U.CN",
          "revLastQ": "N/A",
          "revGrowthLastQ": "unch",
          "revGrowth1qAgo": "unch",
          "revGrowth2qAgo": "unch",
          "grossProfitLastQ": "N/A",
          "operatingIncomeLastQ": "N/A",
          "netIncomeLastQ": "N/A",
          "revLastY": "N/A",
          "revGrowthLastY": "unch",
          "revGrowth1yAgo": "unch",
          "revGrowth2yAgo": "unch",
          "grossProfitLastY": "N/A",
          "operatingIncomeLastY": "N/A",
          "industry_symbol": "VDMS"
        },	
        {
          "equity_symbol": "AAV.TO",
          "revLastQ": "143,027",
          "revGrowthLastQ": "+28.41%",
          "revGrowth1qAgo": "-24.65%",
          "revGrowth2qAgo": "-34.68%",
          "grossProfitLastQ": "95,275",
          "operatingIncomeLastQ": "43,274",
          "netIncomeLastQ": "28,314",
          "revLastY": "964,366",
          "revGrowthLastY": "+96.00%",
          "revGrowth1yAgo": "+100.76%",
          "revGrowth2yAgo": "-2.80%",
          "grossProfitLastY": "719,436",
          "operatingIncomeLastY": "537,267",
          "industry_symbol": "VCMP"
        },
        {
          "equity_symbol": "AIF.TO",
          "revLastQ": "185,232",
          "revGrowthLastQ": "-9.74%",
          "revGrowth1qAgo": "+7.54%",
          "revGrowth2qAgo": "+3.84%",
          "grossProfitLastQ": "N/A",
          "operatingIncomeLastQ": "10,790",
          "netIncomeLastQ": "929",
          "revLastY": "735,451",
          "revGrowthLastY": "+17.60%",
          "revGrowth1yAgo": "+11.45%",
          "revGrowth2yAgo": "-1.10%",
          "grossProfitLastY": "N/A",
          "operatingIncomeLastY": "52,052",
          "industry_symbol": "VTRE"
        }
      ]

async def main():
		sectors, industries, industry_equities = await extract()
		exchange = transform(sectors, industries, industry_equities)
		
		# save_pickle_object(exchange, 'exchange')

		# exchange = load_pickle_object('exchange')

		# for sector in exchange.sectors:
		# 	for industry in sector.industries:
		# 		for equity in industry.equities:
		# 			print(equity.symbol)
		# 			equity.df = equity.download_ohlcv()

		# for sector in exchange.sectors:
		# 	for industry in sector.industries:
		# 		for equity in industry.equities:
		# 				await load(equity, exchange)
		

		# Define the intervals for the initial data download and processing
		# Calculate the start and end dates for each interval
		# now = datetime.datetime.now()
		# intervals_initial = {
		# 		'1m': {'start': now - timedelta(days=5), 'end': now},  # For 1-minute timeframe, retrieve 5 days
		# 		'5m': {'start': now - timedelta(days=5), 'end': now},  # For 5-minute timeframe, retrieve 5 days
		# 		'60m': {'start': now - timedelta(days=5), 'end': now},  # For 1-hour timeframe, retrieve 5 days
		# 		'1d': {'start': now - timedelta(days=5), 'end': now},  # For 1-day timeframe, retrieve 5 days
		# 		'1wk': {'start': now - timedelta(weeks=4), 'end': now - timedelta(weeks=1)},  # For 1-week timeframe, retrieve 1 month, omit current week
		# 		'1mo': {'start': now - timedelta(weeks=16), 'end': now - timedelta(weeks=4)}  # For 1-month timeframe, retrieve 3 months, omit current month
		# }
                
		# Define the intervals for the initial data download and processing
		# period : str
		# Valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
		intervals_initial = {
				# '1m': '5d',  # For 1-minute timeframe, retrieve 5 days
				# '5m': '5d',  # For 5-minute timeframe, retrieve 5 days
				'60m': '5d',  # For 1-hour timeframe, retrieve 5 days
				'1d': '5d',  # For 1-day timeframe, retrieve 5 days
				'1wk': '3mo',  # For 1-week timeframe, retrieve 1 month
				'1mo': '5y'  # For 1-month timeframe, retrieve 3 months
		}

		# TODO: perform check to see if any new industries are included inside of 
		# industries.json that are not within the 'sector_industry_name_mapping' inside of config.py
		#--------------------------------------------------------------------------------------------------
		# equities symbol
		list1 = [
			"BR.TO",
			"HYTN.CN",
			"TPX-B.TO",
			"AMD.NE",
			"INTC.NE",
			"NVDA.NE",
			"PTK.V",
			"SEV.V",
			"HITI.V",
			"IWIN.CN",
			"LOTA.CN",
			"NBLY.TO",
			"NOVC.TO",
			"AMEN.NE",
			"CGX.TO",
			"DIS.NE",
			"NFLX.NE",
			"NTE.V",
			"OAM.V",
			"TBRD.V",
			"WILD.TO",
			"CYM.V",
			"DRX.TO",
			"IVX.V",
			"CAD.V",
			"CSO.V",
			"GRAM.NE",
			"TAAT.CN",
			"COST.NE",
			"DOL.TO",
			"PESO.V",
			"WMT.NE",
			"X.TO",
			"TSU.TO",
			"GH.TO",
			"CRP.TO",
			"GCL.TO",
			"OGO.V",
			"VSOL.NE",
			"BOS.TO",
			"CNO.V",
			"ECO.TO",
			"FNDX.CN",
			"GMG.V",
			"NANO.TO",
			"NEO.TO",
			"VNP.TO",
			"ALYA.TO",
			"BNXA.V",
			"CISC.CN",
			"CTS.TO",
			"DCSI.CN",
			"FARM.V",
			"GIB-A.TO",
			"IBM.NE",
			"KNR.NE",
			"PAID.CN",
			"PBIT.CN",
			"PVT.V",
			"QUIS.V",
			"SFTC.TO",
			"SPOT.V",
			"AVCR.V",
			"BUX.CN",
			"IZO.CN",
			"SONA.CN",
			"TELO.V",
			"COLA.NE",
			"GURU.TO",
			"HILL.V",
			"JSDA.CN",
			"LAS-A.TO",
			"MUSH.V",
			"PRMW.TO",
			"YERB-U.V",
			"RAY-A.TO",
			"TVA-B.TO",
			"GIII.V",
			"PKI.TO",
			"CNJ-P.V",
			"CVX.V",
			"FBF.V",
			"TBL.TO",
			"CKI.TO",
			"ACOG.CN",
			"AEZS.TO",
			"APS.TO",
			"ARCH.V",
			"ASEP.CN",
			"BCT.TO",
			"BMND.NE",
			"CMND.CN",
			"COOL.CN",
			"COV.V",
			"CYBN.NE",
			"CZO.V",
			"DOSE.CN",
			"DRUG.CN",
			"DTC.CN",
			"EPRX.TO",
			"GLAB.CN",
			"HEM.V",
			"IBT.V",
			"MDMA.CN",
			"MMED.NE",
			"MRVL.V",
			"MSCL.V",
			"NGEN.V",
			"ONC.TO",
			"PHRM.CN",
			"SBM.V",
			"TELI.CN",
			"TH.TO",
			"TTI.V",
			"XRTX.V",
			"ELF.TO",
			"GWO.TO",
			"MFC.TO",
			"POW.TO",
			"SFC.TO",
			"READ.CN",
			"Y.TO",
			"DFY.TO",
			"FFH.TO",
			"IFC.TO",
			"CGY.TO",
			"DCM.TO",
			"DXT.TO",
			"GDI.TO",
			"ISV.TO",
			"KBL.TO",
			"KUT.V",
			"RBA.TO",
			"TRI.TO",
			"BHSC.CN",
			"BITE.CN",
			"BOIL.CN",
			"DTEA.V",
			"FRSH.V",
			"GFCO.CN",
			"HBFG.CN",
			"HLF.TO",
			"JWEL.TO",
			"MFI.TO",
			"MOOO.CN",
			"MYLK.V",
			"NGRB.NE",
			"PBH.TO",
			"SAP.TO",
			"SOY.TO",
			"SWP.TO",
			"ATZ.TO",
			"RET-A.V",
			"RET.V",
			"ROOT.TO",
			"CPX.TO",
			"MXG.TO",
			"TA.TO",
			"AIF.TO",
			"BRE.TO",
			"CIGI.TO",
			"CSH-UN.TO",
			"FSV.TO",
			"MEQ.TO",
			"NXLV.V",
			"PKT.V",
			"REAL.TO",
			"SVI.TO",
			"TCN.TO",
			"TRBE.V",
			"YAK.V",
			"CFX.TO",
			"WBE.V",
			"ABND.CN",
			"ABR.V",
			"ACRG-A-U.CN",
			"AGC.CN",
			"AICO.CN",
			"ALCU.CN",
			"AMEN.NE",
			"AMY.V",
			"APS.TO",
			"ARK.V",
			"ARU.V",
			"ASEP.CN",
			"AWKN.CN",
			"AWLI.CN",
			"BITE.CN",
			"BVCI.CN",
			"BWLK.V",
			"BY.CN",
			"BYND.CN",
			"BZ.V",
			"BZAM.CN",
			"CDN.CN",
			"CERT.V",
			"CLIP.V",
			"CMC.V",
			"CMND.CN",
			"CRE.V",
			"CYBT.CN",
			"CZO.V",
			"DCSI.CN",
			"DME.V",
			"DPRO.CN",
			"EDM.V",
			"ELBM.V",
			"ELEM.CN",
			"ENDR.V",
			"ESAU.CN",
			"FFNT.CN",
			"FL.V",
			"GAMA.CN",
			"GAME.V",
			"GFCO.CN",
			"GOAT.CN",
			"HC.NE",
			"HECO.CN",
			"HOLD.NE",
			"IMCC.CN",
			"IWIN.CN",
			"IZO.CN",
			"JZR.V",
			"LAC.TO",
			"LCE.V",
			"LGO.TO",
			"LI.V",
			"LTH.V",
			"MEGA.CN",
			"MHUB.V",
			"MKA.V",
			"MOOO.CN",
			"MYLK.V",
			"NETZ.NE",
			"NPK.TO",
			"NRM.V",
			"NTAR.CN",
			"OGO.V",
			"OIL.CN",
			"OPT.TO",
			"OYL.V",
			"PDO.CN",
			"PKK.CN",
			"PLRB.V",
			"QBAT.CN",
			"QTWO.V",
			"RAGE.V",
			"REX.V",
			"RFLX.CN",
			"RR.CN",
			"RZE.V",
			"SAGE.V",
			"SCM.CN",
			"SLMN.V",
			"SMN.V",
			"SR.V",
			"SUI.V",
			"TAAT.CN",
			"TCF.CN",
			"TGGL.CN",
			"TH.TO",
			"TYUM.CN",
			"UUSA.CN",
			"VCU.V",
			"VOL.V",
			"VSBY.CN",
			"VSOL.NE",
			"WAM.V",
			"WEED.TO",
			"WEST.CN",
			"YERB-U.V",
			"ZAC.V",
			"ALA.TO",
			"ENB.TO",
			"GEI.TO",
			"KEY.TO",
			"PPL.TO",
			"SRR.V",
			"TPZ.TO",
			"TRP.TO",
			"BEW.V",
			"CMI.V",
			"CSCO.NE",
			"ET.TO",
			"NUR.CN",
			"QTRH.TO",
			"TSAT.TO",
			"TTZ.V",
			"VCM.TO",
			"ACD.TO",
			"AFCC-H.V",
			"CHW.TO",
			"EPF.V",
			"GSY.TO",
			"MA.NE",
			"PRL.TO",
			"PYPL.NE",
			"VISA.NE",
			"CUP-U.TO",
			"EMA.TO",
			"FTS.TO",
			"H.TO",
			"AMB.CN",
			"ATD.TO",
			"CTC-A.TO",
			"GBT.TO",
			"IDG.TO",
			"KITS.TO",
			"LNF.TO",
			"PET.TO",
			"ZZZ.TO",
			"CVS.NE",
			"UNH.NE",
			"BDI.TO",
			"EFN.TO",
			"DRM.TO",
			"GDC.TO",
			"MRD.TO",
			"WFC.TO",
			"BMO.TO",
			"BNS.TO",
			"BOFA.NE",
			"CITI.NE",
			"CM.TO",
			"JPM.NE",
			"NA.TO",
			"RY.TO",
			"TD.TO",
			"ABXX.NE",
			"AICO.CN",
			"ARWY.CN",
			"AXE.V",
			"BLN.TO",
			"BWLK.V",
			"CMG.TO",
			"CRM.NE",
			"CSU.TO",
			"CTZ.V",
			"DAY.TO",
			"DCBO.TO",
			"DGHI.V",
			"DND.TO",
			"DSG.TO",
			"DTOL.TO",
			"ENGH.TO",
			"IFSS.NE",
			"INSP.V",
			"INX.V",
			"INXD.NE",
			"IQ.V",
			"KXS.TO",
			"LMN.V",
			"LQWD.V",
			"LSPD.TO",
			"MAPS.V",
			"METG.CN",
			"MHUB.V",
			"MVP.TO",
			"OSS.V",
			"OTEX.TO",
			"PLRB.V",
			"QFOR.TO",
			"QIS.V",
			"RIWI.V",
			"RSS.V",
			"SHOP.TO",
			"SPAI.CN",
			"SPTZ.CN",
			"STER.V",
			"SYZ.TO",
			"TCS.TO",
			"TCXT.V",
			"TGGL.CN",
			"THNC.TO",
			"UBER.NE",
			"URL.CN",
			"VSBY.CN",
			"WISH.V",
			"ARGO.CN",
			"IFOS.V",
			"MGRO.V",
			"NPK.TO",
			"NTR.TO",
			"BRK.NE",
			"IAG.TO",
			"SLF.TO",
			"ACO-X.TO",
			"ACO-Y.TO",
			"BIP-UN.TO",
			"CU.TO",
			"CHEV.NE",
			"CVE.TO",
			"IMO.TO",
			"SU.TO",
			"XOM.NE",
			"ABBV.NE",
			"PFE.NE",
			"AC.TO",
			"CJET.NE",
			"EIF.TO",
			"JET.NE",
			"AAV.TO",
			"ALV.V",
			"AOI.TO",
			"ARX.TO",
			"ATH.TO",
			"AVN.V",
			"AXL.V",
			"BIR.TO",
			"BNE.TO",
			"BTE.TO",
			"CDA.V",
			"CDR.TO",
			"CEC.V",
			"CEI.V",
			"CJ.TO",
			"CNE.TO",
			"CNQ.TO",
			"CPG.TO",
			"CR.TO",
			"DME.V",
			"EOG.V",
			"ERF.TO",
			"FEC.TO",
			"FO.V",
			"FRU.TO",
			"GASX.V",
			"GTE.TO",
			"HAM.V",
			"HEVI.V",
			"HME.V",
			"HWX.TO",
			"IPCO.TO",
			"IPO.TO",
			"JEV.V",
			"JOY.TO",
			"KEC.TO",
			"KEI.TO",
			"KEL.TO",
			"LCX.V",
			"LGN.V",
			"LOU.V",
			"MCF.V",
			"MEG.TO",
			"NSE.V",
			"NVA.TO",
			"OBE.TO",
			"OIL.CN",
			"ORC-B.V",
			"OVV.TO",
			"OYL.V",
			"PEY.TO",
			"PNE.TO",
			"POU.TO",
			"PRQ.TO",
			"PSK.TO",
			"PXT.TO",
			"RBY.TO",
			"RECO.V",
			"RHC.V",
			"ROK.V",
			"SDE.TO",
			"SEI.V",
			"SGY.TO",
			"SOIL.TO",
			"SOU.V",
			"TAO.V",
			"TCF.CN",
			"TNZ.TO",
			"TOU.TO",
			"TPC.V",
			"TPL.V",
			"TVE.TO",
			"VET.TO",
			"VLE.TO",
			"VUX.V",
			"WCP.TO",
			"WIL.V",
			"YGR.TO",
			"ADN.TO",
			"CFP.TO",
			"GDL.TO",
			"IFP.TO",
			"SJ.TO",
			"WFG.TO",
			"AD-UN.TO",
			"AGF-B.TO",
			"AIM.TO",
			"AIVC.V",
			"BAM.TO",
			"BBUC.TO",
			"BCBN.NE",
			"BGI-UN.TO",
			"BK.TO",
			"BN.TO",
			"BNK.TO",
			"BVOF-B.CN",
			"CEF-U.TO",
			"CEF.TO",
			"CGI.TO",
			"CIX.TO",
			"CLP-UN.TO",
			"CVG.TO",
			"CYB.TO",
			"DF.TO",
			"DFN.TO",
			"DGS.TO",
			"DS.TO",
			"EIT-UN.TO",
			"ELC.V",
			"ENI-UN.TO",
			"ENS.TO",
			"ETHC.NE",
			"FAP.TO",
			"FFN.TO",
			"FIH-U.TO",
			"FSZ.TO",
			"FTN.TO",
			"FW.V",
			"GCG.TO",
			"GDV.TO",
			"GOAT.CN",
			"HFPC-U.TO",
			"IDK.CN",
			"IGM.TO",
			"INC-UN.TO",
			"LBS.TO",
			"LCS.TO",
			"LFE.TO",
			"LITT.V",
			"MBAI.CN",
			"MID-UN.TO",
			"MLC.NE",
			"MMP-UN.TO",
			"MONT.V",
			"MSRE-UN.TO",
			"NETZ.NE",
			"OLY.TO",
			"ONEX.TO",
			"PDV.TO",
			"PHYS-U.TO",
			"PHYS.TO",
			"PIC-A.TO",
			"PRM.TO",
			"PSLV-U.TO",
			"PSLV.TO",
			"PTI-UN.TO",
			"PWI.TO",
			"RBN-UN.TO",
			"RCG.TO",
			"RS.TO",
			"SBC.TO",
			"SII.TO",
			"SOL.CN",
			"SPPP.TO",
			"STCK.TO",
			"TIE.V",
			"TINY.V",
			"TLP-UN.CN",
			"UNC.TO",
			"URB-A.TO",
			"URB.TO",
			"VST.CN",
			"WED.V",
			"WI.V",
			"XTD.TO",
			"RSI.TO",
			"TYUM.CN",
			"BCE.TO",
			"CCA.TO",
			"CGO.TO",
			"QBR-B.TO",
			"RCI-B.TO",
			"T.TO",
			"TGO.TO",
			"VZ.NE",
			"FHYD.V",
			"NFI.TO",
			"TSLA.NE",
			"VMC.V",
			"NKE.NE",
			"SHOE.CN",
			"ASTL.TO",
			"CIA.TO",
			"LIF.TO",
			"STLC.TO",
			"TSL.TO",
			"AKT-A.TO",
			"ESI.TO",
			"PD.TO",
			"PHX.TO",
			"SDI.V",
			"WRG.TO",
			"BBU-UN.TO",
			"DE.V",
			"DIV.TO",
			"HON.NE",
			"ABX.TO",
			"AE.V",
			"AEM.TO",
			"AGC.CN",
			"AGI.TO",
			"ALTA.V",
			"AMQ.CN",
			"AMRQ.V",
			"AMX.V",
			"ANK.V",
			"ARIC.V",
			"ARIS.TO",
			"ARTG.V",
			"ASE.CN",
			"ATX.V",
			"AU.V",
			"AUAU.V",
			"AUEN.V",
			"AUOZ.CN",
			"BAU.V",
			"BCM.V",
			"BLDS.V",
			"BLLG.CN",
			"BNN.CN",
			"BRW.V",
			"BSR.V",
			"BTO.TO",
			"BTR.V",
			"BYN.V",
			"CBR.V",
			"CEE.TO",
			"CERT.V",
			"CG.TO",
			"CGC.V",
			"CNL.TO",
			"CTOC.CN",
			"CXB.TO",
			"DCLI.CN",
			"DEX.V",
			"DLTA.V",
			"DPM.TO",
			"DYG.V",
			"EDG.V",
			"EDV.TO",
			"ELD.TO",
			"ELE.V",
			"ELEM.CN",
			"ELO.TO",
			"EQX.TO",
			"FDR.V",
			"FISH.V",
			"FNAU.CN",
			"FNV.TO",
			"FOR.V",
			"FVI.TO",
			"GAL.V",
			"GAU.TO",
			"GBRC.V",
			"GG.V",
			"GGC.CN",
			"GGO.V",
			"GLDC.V",
			"GMR.CN",
			"GMV.V",
			"GOLD.TO",
			"GPAC.V",
			"GPG.V",
			"GRHK.CN",
			"GRZ.V",
			"GSHR.V",
			"GSRI.CN",
			"GSTM.V",
			"GTCH.CN",
			"GTWO.V",
			"GUS.V",
			"GWM.V",
			"GXS.V",
			"HARD.CN",
			"HIGH.V",
			"HMR.V",
			"HSTR.V",
			"HWG.CN",
			"IAU.TO",
			"IGO.V",
			"IMG.TO",
			"INCA.V",
			"IRV.CN",
			"JAG.TO",
			"K.TO",
			"KNT.TO",
			"KRI.V",
			"KRR.TO",
			"LAB.V",
			"LGC.V",
			"LIO.V",
			"LME.V",
			"LORD.V",
			"LUG.TO",
			"LUM.V",
			"LVG.V",
			"LVX.V",
			"MAI.V",
			"MAU.V",
			"MAW.V",
			"MFG.V",
			"MGG.V",
			"MKO.V",
			"MMY.V",
			"MND.TO",
			"MSM.CN",
			"NCAU.V",
			"NCLR.CN",
			"NFG.V",
			"NG.TO",
			"NGD.TO",
			"NGE.V",
			"NGT.TO",
			"NPR.V",
			"ODV.V",
			"OGC.TO",
			"OGN.V",
			"OLA.TO",
			"ONYX.V",
			"OR.TO",
			"ORA.TO",
			"OSI.V",
			"OSK.TO",
			"PA.V",
			"PAAS.TO",
			"PALI.V",
			"PGOL.CN",
			"PHNM.V",
			"PMC.CN",
			"PRB.TO",
			"PRU.TO",
			"PUMA.V",
			"QIM.CN",
			"RAGE.V",
			"RBX.V",
			"RDS.V",
			"RGC.V",
			"RGD.V",
			"RIO.V",
			"RISE.CN",
			"RML.V",
			"RPX.V",
			"RSM.V",
			"RUP.TO",
			"RVG.V",
			"SEA.TO",
			"SGD.V",
			"SIG.CN",
			"SOMA.V",
			"SPA.V",
			"SSL.TO",
			"SSRM.TO",
			"STLR.TO",
			"SUP.V",
			"TBK.V",
			"THX.V",
			"TIN.V",
			"TROY.CN",
			"TUD.V",
			"TXG.TO",
			"USGD.CN",
			"VAU.V",
			"VG.V",
			"VGCX.TO",
			"VIO.V",
			"VSR.V",
			"WDO.TO",
			"WGO.V",
			"WHN.V",
			"WPM.TO",
			"WRLG.V",
			"WRR.V",
			"WVM.V",
			"XIM.V",
			"ZON.V",
			"AZ.V",
			"BA.NE",
			"BBD-B.TO",
			"CAE.TO",
			"DPRO.CN",
			"FLY.V",
			"FTG.TO",
			"HRX.TO",
			"KWE.V",
			"MAL.TO",
			"MAXQ.NE",
			"MDA.TO",
			"VOL.V",
			"ATD.TO",
			"EMP-A.TO",
			"JWEL.TO",
			"L.TO",
			"MFI.TO",
			"MRU.TO",
			"NWC.TO",
			"PBH.TO",
			"PRMW.TO",
			"SAP.TO",
			"WN.TO",
			"OPTI.CN",
			"PEAS.V",
			"EMP-A.TO",
			"L.TO",
			"MRU.TO",
			"NWC.TO",
			"WN.TO",
			"BHC.TO",
			"CSH-UN.TO",
			"SIA.TO",
			"TLRY.TO",
			"ACT.CN",
			"BRM.V",
			"DESG.NE",
			"DST.CN",
			"QST.V",
			"SHRC.CN",
			"TMG.V",
			"CLS.TO",
			"HEAT.CN",
			"WIFI.CN",
			"ALC.TO",
			"WTE.TO",
			"CAS.TO",
			"CCL-B.TO",
			"IFX.V",
			"NEXE.V",
			"RPI-UN.TO",
			"SXP.TO",
			"TCL-A.TO",
			"WPK.TO",
			"CWB.TO",
			"EQB.TO",
			"LB.TO",
			"VBNK.TO",
			"ABND.CN",
			"ELVA.TO",
			"HMM-A.TO",
			"HPS-A.TO",
			"LPS.V",
			"BCE.TO",
			"CCA.TO",
			"QBR-B.TO",
			"RCI-B.TO",
			"T.TO",
			"AI.TO",
			"DLCG.TO",
			"ECN.TO",
			"FC.TO",
			"FN.TO",
			"MKP.TO",
			"TF.TO",
			"AAPL.NE",
			"HC.NE",
			"LNR.TO",
			"MG.TO",
			"MRE.TO",
			"WPRT.TO",
			"XTC.TO",
			"APR-UN.TO",
			"ASG.V",
			"BLO.CN",
			"EVMT.V",
			"HTL.TO",
			"NGMD.V",
			"PINK.V",
			"QIPT.TO",
			"TLT.V",
			"VPT.V",
			"MTL.TO",
			"TFII.TO",
			"ADW-A.TO",
			"CSW-A.TO",
			"DWS.V",
			"TOY.TO",
			"TWC.TO",
			"AAV.TO",
			"AOI.TO",
			"ARX.TO",
			"ATH.TO",
			"BIR.TO",
			"BTE.TO",
			"CNQ.TO",
			"CPG.TO",
			"CVE.TO",
			"ERF.TO",
			"FRU.TO",
			"HWX.TO",
			"IMO.TO",
			"IPCO.TO",
			"KEL.TO",
			"MATR.TO",
			"MEG.TO",
			"NVA.TO",
			"PD.TO",
			"PEY.TO",
			"POU.TO",
			"PSI.TO",
			"PSK.TO",
			"PXT.TO",
			"SES.TO",
			"SU.TO",
			"TOU.TO",
			"TPZ.TO",
			"TVE.TO",
			"VET.TO",
			"WCP.TO",
			"AND.TO",
			"CJT.TO",
			"PDO.CN",
			"TTNM.TO",
			"UPS.NE",
			"AAG.V",
			"AAN.V",
			"ABA.V",
			"ABR.V",
			"ADZN.V",
			"AFM.V",
			"AGX.V",
			"AHR.V",
			"AJN.CN",
			"ALCU.CN",
			"ALDE.V",
			"ALS.TO",
			"AMC.TO",
			"AMPS.CN",
			"AMY.V",
			"APN.V",
			"ARS.CN",
			"ATOM.V",
			"ATY.V",
			"AWLI.CN",
			"AZM.V",
			"AZT.V",
			"BATX.CN",
			"BAY.V",
			"BEX.V",
			"BKM.V",
			"BMR.V",
			"BOLT.CN",
			"BRO.V",
			"BULL.CN",
			"BY.CN",
			"BZ.V",
			"CC.CN",
			"CCCM.V",
			"CCE.V",
			"CD.V",
			"CDB.V",
			"CDN.CN",
			"CDPR.CN",
			"CNC.V",
			"CNRI.V",
			"CNX.V",
			"COSA.V",
			"CPAU.V",
			"CPS.V",
			"CRE.V",
			"CRES.CN",
			"CUSN.V",
			"CVV.V",
			"CVW.V",
			"DAN.V",
			"DBG.V",
			"DEFN.V",
			"DG.V",
			"DLP.V",
			"DMX.V",
			"EBR.CN",
			"ECOR.TO",
			"EDDY.V",
			"EDM.V",
			"ELBM.V",
			"ELEC.V",
			"EMM.V",
			"EMNT.V",
			"EMO.V",
			"EMX.V",
			"EPL.V",
			"ERKA.CN",
			"ESK.V",
			"ESPN.V",
			"ETG.TO",
			"ETL.V",
			"EVNI.V",
			"FAR.TO",
			"FCLI.V",
			"FE.CN",
			"FIL.TO",
			"FIN.V",
			"FL.V",
			"FMC.V",
			"FMS.V",
			"FNI.CN",
			"FOM.TO",
			"FOX.CN",
			"FPC.V",
			"FPX.V",
			"FWZ.V",
			"GAMA.CN",
			"GCC.CN",
			"GDIG.CN",
			"GEL.V",
			"GEO.TO",
			"GGI.V",
			"GIGA.V",
			"GLAD.V",
			"GLO.TO",
			"GMA.V",
			"GPH.V",
			"GQC.V",
			"GRAT.V",
			"HAN.V",
			"HAR.V",
			"HECO.CN",
			"HERC.CN",
			"HPQ.V",
			"HUNT.CN",
			"HZ.CN",
			"IBAT.CN",
			"IMCX.CN",
			"INTR.V",
			"IVN.TO",
			"JZR.V",
			"KLD.V",
			"LAC.TO",
			"LBNK.V",
			"LCE.V",
			"LEM.V",
			"LGO.TO",
			"LI.V",
			"LIFT.V",
			"LIM.CN",
			"LIRC.TO",
			"LIS.V",
			"LIT.V",
			"LITH.V",
			"LITS.NE",
			"LLG.V",
			"LRA.V",
			"LTH.V",
			"LUCA.V",
			"M.CN",
			"MAXX.CN",
			"MD.V",
			"MDI.TO",
			"MEGA.CN",
			"MKA.V",
			"MKR.V",
			"MLP.V",
			"MMA.V",
			"MMET.CN",
			"MML.CN",
			"MMS.V",
			"MN.V",
			"MOLY.NE",
			"MON.V",
			"MSR.V",
			"MUN.V",
			"NB.TO",
			"NBM.V",
			"NCX.V",
			"NGC.V",
			"NGEX.V",
			"NICN.V",
			"NICU.V",
			"NILI.V",
			"NIM.V",
			"NIO.V",
			"NKG.V",
			"NKL.V",
			"NOAL.V",
			"NOU.V",
			"NRM.V",
			"NTMC.CN",
			"NVLH.CN",
			"NVLI.CN",
			"NWST.V",
			"NWX.V",
			"OCO.V",
			"OIII.V",
			"OM.V",
			"PE.V",
			"PEGA.V",
			"PGE.V",
			"PGX.V",
			"PGZ.V",
			"PHOS.CN",
			"PJX.V",
			"PLAN.V",
			"PM.CN",
			"PMET.TO",
			"PML.V",
			"PNPN.V",
			"PNRG.CN",
			"PNRL.V",
			"POWR.CN",
			"PRIZ.CN",
			"PRR.CN",
			"PRYM.TO",
			"PWM.V",
			"QBAT.CN",
			"QREE.CN",
			"QTWO.V",
			"RCK.V",
			"REG.V",
			"REX.V",
			"RFLX.CN",
			"RR.CN",
			"SAGE.V",
			"SALT.V",
			"SCM.CN",
			"SCZ.V",
			"SEAG.CN",
			"SGML.V",
			"SHOW.CN",
			"SKE.TO",
			"SKRR.V",
			"SLI.V",
			"SLV.CN",
			"SMD.V",
			"SME.V",
			"SMN.V",
			"SR.V",
			"SRA.V",
			"SRG.V",
			"SRS.CN",
			"STE.V",
			"STGX.CN",
			"STK.CN",
			"STS.V",
			"STU.V",
			"STUD.V",
			"SUI.V",
			"SYH.V",
			"TAU.V",
			"TCEC.CN",
			"TDG.V",
			"TECK-B.TO",
			"TIG.V",
			"TK.V",
			"TMAS.CN",
			"TN.CN",
			"TOC.CN",
			"TORQ.V",
			"UCU.V",
			"ULTH.CN",
			"UUSA.CN",
			"UX.CN",
			"VBAM.CN",
			"VLT.V",
			"VRTX.CN",
			"VUL.V",
			"VZLA.V",
			"WEST.CN",
			"WHY.V",
			"WMK.V",
			"WML.V",
			"WRN.TO",
			"XRI.CN",
			"ZNG.V",
			"AMZN.NE",
			"NTAR.CN",
			"ADK.V",
			"AIAI.CN",
			"KSI.TO",
			"NDAT.CN",
			"NURS.V",
			"THNK.V",
			"TRUE.CN",
			"UDOC.CN",
			"VHI.TO",
			"CHE-UN.TO",
			"FAT.CN",
			"GRA.TO",
			"MX.TO",
			"SWAN.V",
			"AC.TO",
			"ATRL.TO",
			"ATS.TO",
			"BBD-B.TO",
			"BBU-UN.TO",
			"BDGI.TO",
			"BLDP.TO",
			"BYD.TO",
			"CAE.TO",
			"CJT.TO",
			"CNR.TO",
			"CP.TO",
			"EFN.TO",
			"EIF.TO",
			"FTT.TO",
			"GFL.TO",
			"MTL.TO",
			"RCH.TO",
			"RUS.TO",
			"STN.TO",
			"TFII.TO",
			"TIH.TO",
			"TRI.TO",
			"WCN.TO",
			"WSP.TO",
			"WTE.TO",
			"PBL.TO",
			"PMKR.V",
			"RVLY.V",
			"GIL.TO",
			"GOOS.TO",
			"UNI.TO",
			"EQ.V",
			"ILLM.TO",
			"ACO-X.TO",
			"ALA.TO",
			"AQN.TO",
			"BEP-UN.TO",
			"BIP-UN.TO",
			"BLX.TO",
			"CPX.TO",
			"CU.TO",
			"EMA.TO",
			"FTS.TO",
			"H.TO",
			"INE.TO",
			"NPI.TO",
			"SPB.TO",
			"TA.TO",
			"ARE.TO",
			"ATRL.TO",
			"BDGI.TO",
			"BDT.TO",
			"STN.TO",
			"WSP.TO",
			"APM.V",
			"AYA.TO",
			"BIG.V",
			"BNKR.V",
			"DV.V",
			"EML.V",
			"FR.TO",
			"GSVR.V",
			"IPT.V",
			"KTN.V",
			"KUYA.CN",
			"MAG.TO",
			"RSLV.V",
			"RSMX.V",
			"SVE.V",
			"SVM.TO",
			"SVRS.V",
			"ZAC.V",
			"CGII.CN",
			"KPT.TO",
			"PG.NE",
			"TRZ.TO",
			"AFN.TO",
			"BUI.TO",
			"CUB.V",
			"GPV.V",
			"LEV.TO",
			"TGH.V",
			"AAWH-U.CN",
			"ACRG-A-U.CN",
			"AYR-A.CN",
			"BAMM.CN",
			"BHC.TO",
			"BNXT.CN",
			"BZAM.CN",
			"CANB.V",
			"CDVA.CN",
			"CL.CN",
			"CPH.TO",
			"CRDL.TO",
			"CRON.TO",
			"CURA.TO",
			"CXXI.CN",
			"DB.V",
			"DHT-UN.TO",
			"EPIC.CN",
			"FFNT.CN",
			"GDNS.CN",
			"GLAS-A-U.NE",
			"GRIN.CN",
			"GTII.CN",
			"GUD.TO",
			"GWAY.CN",
			"HLS.TO",
			"HUGE.CN",
			"IMCC.CN",
			"INNO.CN",
			"JUSH.CN",
			"LOVE.V",
			"LOWL.CN",
			"LSL.V",
			"MDP.TO",
			"MPH.V",
			"MRMD.CN",
			"OGI.TO",
			"OILS.CN",
			"PCLO.V",
			"PLTH.CN",
			"RIV.CN",
			"ROMJ.V",
			"RX.V",
			"SBBC.V",
			"SE.CN",
			"SHWZ.NE",
			"STEM.CN",
			"TIUM-U.CN",
			"TLRY.TO",
			"TRUL.CN",
			"TSND.TO",
			"VEXT.CN",
			"VRNO.NE",
			"WEED.TO",
			"XTRX.CN",
			"ZYUS.V",
			"ATS.TO",
			"BLDP.TO",
			"ENW.V",
			"NXH.V",
			"SIS.TO",
			"TLA.V",
			"VLN.TO",
			"CHP-UN.TO",
			"CRT-UN.TO",
			"FCD-UN.TO",
			"FCR-UN.TO",
			"PLZ-UN.TO",
			"PMZ-UN.TO",
			"REI-UN.TO",
			"SGR-U.TO",
			"SGR-UN.TO",
			"SRU-UN.TO",
			"BEI-UN.TO",
			"CAR-UN.TO",
			"DRR-U.TO",
			"ERE-UN.TO",
			"HOM-U.TO",
			"HOM-UN.TO",
			"IIP-UN.TO",
			"KMP-UN.TO",
			"MAR-UN.V",
			"MHC-U.TO",
			"MHC-UN.TO",
			"MI-UN.TO",
			"MRG-UN.TO",
			"BAM.TO",
			"BMO.TO",
			"BN.TO",
			"BNS.TO",
			"CIX.TO",
			"CM.TO",
			"CWB.TO",
			"DFY.TO",
			"EQB.TO",
			"FFH.TO",
			"GSY.TO",
			"GWO.TO",
			"IAG.TO",
			"IFC.TO",
			"IGM.TO",
			"LB.TO",
			"MFC.TO",
			"NA.TO",
			"NVEI.TO",
			"ONEX.TO",
			"POW.TO",
			"RY.TO",
			"SII.TO",
			"SLF.TO",
			"TD.TO",
			"TSU.TO",
			"X.TO",
			"FLT.V",
			"VRAI.CN",
			"AIF.TO",
			"AP-UN.TO",
			"BEI-UN.TO",
			"CAR-UN.TO",
			"CHP-UN.TO",
			"CIGI.TO",
			"CRR-UN.TO",
			"CRT-UN.TO",
			"DIR-UN.TO",
			"FCR-UN.TO",
			"FSV.TO",
			"GRT-UN.TO",
			"HR-UN.TO",
			"IIP-UN.TO",
			"KMP-UN.TO",
			"NWH-UN.TO",
			"PMZ-UN.TO",
			"REI-UN.TO",
			"SRU-UN.TO",
			"SVI.TO",
			"TCN.TO",
			"NSCI.V",
			"PNG.V",
			"AX-UN.TO",
			"CRR-UN.TO",
			"HR-UN.TO",
			"MPCT-UN.TO",
			"MR-UN.TO",
			"MRT-UN.TO",
			"NET-UN.V",
			"NWH-UN.TO",
			"CHR.TO",
			"ABX.TO",
			"AEM.TO",
			"AQN.TO",
			"ATD.TO",
			"BAM.TO",
			"BCE.TO",
			"BIP-UN.TO",
			"BMO.TO",
			"BN.TO",
			"BNS.TO",
			"CAE.TO",
			"CAR-UN.TO",
			"CCL-B.TO",
			"CCO.TO",
			"CM.TO",
			"CNQ.TO",
			"CNR.TO",
			"CP.TO",
			"CSU.TO",
			"CTC-A.TO",
			"CVE.TO",
			"DOL.TO",
			"EMA.TO",
			"ENB.TO",
			"FM.TO",
			"FNV.TO",
			"FSV.TO",
			"FTS.TO",
			"GIB-A.TO",
			"GIL.TO",
			"H.TO",
			"IFC.TO",
			"IMO.TO",
			"K.TO",
			"L.TO",
			"MFC.TO",
			"MG.TO",
			"MRU.TO",
			"NA.TO",
			"NTR.TO",
			"OTEX.TO",
			"POW.TO",
			"PPL.TO",
			"QSR.TO",
			"RCI-B.TO",
			"RY.TO",
			"SAP.TO",
			"SHOP.TO",
			"SLF.TO",
			"SU.TO",
			"T.TO",
			"TD.TO",
			"TECK-B.TO",
			"TOU.TO",
			"TRI.TO",
			"TRP.TO",
			"WCN.TO",
			"WN.TO",
			"WPM.TO",
			"WSP.TO",
			"BYD.TO",
			"PLC.TO",
			"WOLF.V",
			"BILD.V",
			"FORA.TO",
			"GOOG.NE",
			"META.NE",
			"SBIO.V",
			"BB.TO",
			"BTQ.NE",
			"BVCI.CN",
			"BYND.CN",
			"CLIP.V",
			"CPLF.TO",
			"CTRL.V",
			"CVO.TO",
			"CYBT.CN",
			"HAI.TO",
			"MDF.TO",
			"MIM.V",
			"MOGO.TO",
			"MSFT.NE",
			"NBVA.V",
			"NFTX.NE",
			"NOW.V",
			"NVEI.TO",
			"OPT.TO",
			"PAY.TO",
			"PKK.CN",
			"RAIL.CN",
			"SCPE.CN",
			"STC.TO",
			"TC.TO",
			"TIXT.TO",
			"TOI.V",
			"VERS.NE",
			"GSI.V",
			"SCAN.V",
			"SECU.V",
			"XX.V",
			"ZDC.V",
			"AW-UN.TO",
			"BPF-UN.TO",
			"COHO.V",
			"KEG-UN.TO",
			"MCDS.NE",
			"MTY.TO",
			"ODD.V",
			"PZA.TO",
			"QSR.TO",
			"SBUX.NE",
			"SRV-UN.TO",
			"BIPC.TO",
			"EVGN.V",
			"SPB.TO",
			"ATZ.TO",
			"CTC-A.TO",
			"DOL.TO",
			"DOO.TO",
			"GIL.TO",
			"GOOS.TO",
			"LNR.TO",
			"MG.TO",
			"MTY.TO",
			"PET.TO",
			"QSR.TO",
			"TOY.TO",
			"ZZZ.TO",
			"MENE.V",
			"ALYA.TO",
			"BB.TO",
			"BITF.TO",
			"CLS.TO",
			"CMG.TO",
			"CPLF.TO",
			"CSU.TO",
			"CTS.TO",
			"CVO.TO",
			"DCBO.TO",
			"DND.TO",
			"DSG.TO",
			"ENGH.TO",
			"GIB-A.TO",
			"HUT.TO",
			"KXS.TO",
			"LSPD.TO",
			"OTEX.TO",
			"QTRH.TO",
			"SFTC.TO",
			"SHOP.TO",
			"SYZ.TO",
			"TCS.TO",
			"HD.NE",
			"AUUA.V",
			"DIR-UN.TO",
			"GRT-UN.TO",
			"NXR-UN.TO",
			"PRV-UN.TO",
			"ABRA.V",
			"AEMC.V",
			"ALEX.V",
			"AMK.V",
			"ARK.V",
			"ARU.V",
			"ASTR.V",
			"AUCU.CN",
			"AWM.V",
			"AZS.V",
			"BBB.V",
			"BME.V",
			"BRC.V",
			"BRVO.V",
			"BWCG.V",
			"CAM.V",
			"CAPT.V",
			"CBG.V",
			"CFE.CN",
			"CGG.TO",
			"CKG.V",
			"CLIC.V",
			"CN.V",
			"COMT.CN",
			"CUAU.CN",
			"DNG.TO",
			"DSLV.V",
			"EDR.TO",
			"EMPR.V",
			"EMPS.CN",
			"ENDR.V",
			"ER.CN",
			"ESAU.CN",
			"FTZ.V",
			"GATO.TO",
			"GBU.V",
			"GGD.TO",
			"GMIN.TO",
			"GOT.V",
			"GSPR.V",
			"ITR.V",
			"KDK.V",
			"LBC.V",
			"MMG.V",
			"MRZ.V",
			"MTA.V",
			"MUX.TO",
			"NAU.V",
			"NEXU.CN",
			"NUAG.TO",
			"NVRO.CN",
			"OCG.V",
			"PEX.V",
			"PPTA.TO",
			"PTM.TO",
			"RRI.V",
			"SAND.CN",
			"SBMI.V",
			"SCOT.V",
			"SIL.TO",
			"SLS.TO",
			"SLVR.V",
			"SM.V",
			"SNAG.V",
			"SSV.V",
			"SSVR.V",
			"STRR.V",
			"TBX.V",
			"TFPM.TO",
			"TUO.V",
			"VML.V",
			"VOXR.TO",
			"WAM.V",
			"WEX.V",
			"ADEN.TO",
			"DBM.TO",
			"FTT.TO",
			"RUS.TO",
			"TIH.TO",
			"WJX.TO",
			"AP-UN.TO",
			"BTB-UN.TO",
			"D-UN.TO",
			"INO-UN.TO",
			"TNT-UN.TO",
			"BIGG.CN",
			"BITF.TO",
			"BITK.V",
			"CBIT.V",
			"CF.TO",
			"COIN.NE",
			"CXI.TO",
			"DEFI.NE",
			"DELX.V",
			"DMGI.V",
			"FRNT.V",
			"GLXY.TO",
			"GS.NE",
			"HIVE.V",
			"HODL.CN",
			"HOLD.NE",
			"HUT.TO",
			"MNS.TO",
			"MNT.TO",
			"NDA.V",
			"PNP.TO",
			"SATO.V",
			"XAU.TO",
			"CTH.V",
			"MOX.V",
			"SGQ.V",
			"API.CN",
			"CAKE.CN",
			"CCO.TO",
			"DML.TO",
			"EFR.TO",
			"EU.V",
			"FCU.TO",
			"FIND.V",
			"FUU.V",
			"GREN.CN",
			"GXU.V",
			"ISO.V",
			"LUR.CN",
			"NF.CN",
			"NXE.TO",
			"SASK.CN",
			"SUU.V",
			"TMC.V",
			"U-U.TO",
			"U-UN.TO",
			"URC.TO",
			"URE.TO",
			"WUC.CN",
			"DOO.TO",
			"AQN.TO",
			"ARR.TO",
			"BEP-UN.TO",
			"BEPC.TO",
			"BLX.TO",
			"GIP.V",
			"GRB.V",
			"INE.TO",
			"LCFS.TO",
			"NPI.TO",
			"PIF.TO",
			"RE.V",
			"REVV.V",
			"UGE.V",
			"WEB.V",
			"CEU.TO",
			"CFW.TO",
			"EFX.TO",
			"HWO.TO",
			"MATR.TO",
			"MCB.TO",
			"NOA.TO",
			"PSD.TO",
			"PSI.TO",
			"SHLE.TO",
			"STEP.TO",
			"TCW.TO",
			"TOT.TO",
			"TVK.TO",
			"ABX.TO",
			"AEM.TO",
			"AGI.TO",
			"ASTL.TO",
			"BTO.TO",
			"CCL-B.TO",
			"CFP.TO",
			"CG.TO",
			"CS.TO",
			"DPM.TO",
			"ELD.TO",
			"EQX.TO",
			"ERO.TO",
			"FIL.TO",
			"FM.TO",
			"FNV.TO",
			"FR.TO",
			"FVI.TO",
			"HBM.TO",
			"IFP.TO",
			"IMG.TO",
			"IVN.TO",
			"K.TO",
			"KNT.TO",
			"LAC.TO",
			"LIF.TO",
			"LUG.TO",
			"LUN.TO",
			"MAG.TO",
			"MX.TO",
			"NG.TO",
			"NGD.TO",
			"NTR.TO",
			"OGC.TO",
			"OLA.TO",
			"OR.TO",
			"OSK.TO",
			"PAAS.TO",
			"SEA.TO",
			"SIL.TO",
			"SJ.TO",
			"SSL.TO",
			"SSRM.TO",
			"STLC.TO",
			"TCL-A.TO",
			"TECK-B.TO",
			"TXG.TO",
			"WDO.TO",
			"WFG.TO",
			"WPK.TO",
			"WPM.TO",
			"CRRX.TO",
			"DNTL.TO",
			"DR.TO",
			"EXE.TO",
			"KDA.V",
			"NLH.V",
			"NPTH.V",
			"PHA.V",
			"SIA.TO",
			"WELL.TO",
			"MRC.TO",
			"UFC.V",
			"YEG.V",
			"BLM.V",
			"CMC.V",
			"ECM.V",
			"EWK.V",
			"GFL.TO",
			"LUX.CN",
			"PLAS.CN",
			"ROOF.V",
			"SES.TO",
			"VCI.V",
			"VTX.V",
			"WCN.TO",
			"YES.V",
			"ARG.TO",
			"ASCU.TO",
			"CS.TO",
			"CUU.V",
			"ECU.V",
			"ERO.TO",
			"FM.TO",
			"HBM.TO",
			"HCH.V",
			"HCU.V",
			"IE.TO",
			"III.TO",
			"LA.V",
			"LUN.TO",
			"MARI.TO",
			"QCCU.V",
			"SLMN.V",
			"TKO.TO",
			"TM.V",
			"TWO.V",
			"VCU.V",
			"AEP.V",
			"ABXX.NE",
			"AE.V",
			"AIVC.V",
			"AMD.NE",
			"AMQ.CN",
			"AMRQ.V",
			"AMZN.NE",
			"ARTG.V",
			"BDGI.TO",
			"BDT.TO",
			"BIG.V",
			"BILD.V",
			"BLN.TO",
			"BNN.CN",
			"BUX.CN",
			"CAKE.CN",
			"CDR.TO",
			"CGII.CN",
			"CLS.TO",
			"CNJ-P.V",
			"CNO.V",
			"CPH.TO",
			"CRM.NE",
			"CVX.V",
			"DCM.TO",
			"DE.V",
			"DEFI.NE",
			"DHT-UN.TO",
			"DML.TO",
			"DMX.V",
			"DRX.TO",
			"ETHC.NE",
			"EU.V",
			"EVNI.V",
			"FAR.TO",
			"FTG.TO",
			"GAU.TO",
			"GBU.V",
			"GLAS-A-U.NE",
			"GLXY.TO",
			"GMIN.TO",
			"GPAC.V",
			"GRIN.CN",
			"GRZ.V",
			"GSI.V",
			"HBFG.CN",
			"HERC.CN",
			"HMM-A.TO",
			"HPS-A.TO",
			"HYTN.CN",
			"IBT.V",
			"IQ.V",
			"ISO.V",
			"KDA.V",
			"LITS.NE",
			"LMN.V",
			"MCB.TO",
			"MDA.TO",
			"META.NE",
			"MML.CN",
			"MON.V",
			"NFLX.NE",
			"NGEX.V",
			"NOVC.TO",
			"NVDA.NE",
			"NXE.TO",
			"OILS.CN",
			"OLY.TO",
			"OSS.V",
			"PBL.TO",
			"PJX.V",
			"PNG.V",
			"PRL.TO",
			"QFOR.TO",
			"RML.V",
			"SEI.V",
			"SGD.V",
			"SGQ.V",
			"SHLE.TO",
			"SHOW.CN",
			"SJ.TO",
			"STK.CN",
			"SUNN.NE",
			"TBK.V",
			"THNC.TO",
			"TMG.V",
			"TROY.CN",
			"TRUE.CN",
			"TTZ.V",
			"TVK.TO",
			"U-U.TO",
			"U-UN.TO",
			"UBER.NE",
			"URE.TO",
			"VHI.TO",
			"VSR.V",
			"WMK.V",
			"WUC.CN",
			"ZNG.V",
			"BLCO.TO",
			"OTC.V",
			"ZEN.V",
			"ACQ.TO",
			"BNRE.TO",
			"DII-B.TO",
			"RCH.TO",
			"BRAG.TO",
			"GAME.V",
			"GET.CN",
			"GOOD.V"
		]
		
		# list1 = ["ERO.TO", "GWO.TO", "MFC.TO", "SHOP.TO", "TLRY.TO", "BIGG.CN", "PRL.TO"]
		# list1 = ["BTC-USD", "ETH-USD"]


		# print(':========STEP 1=========:')
		# dataframes = Data.download_ohlcv(list1, intervals_initial, market_hours=False)
		
		# print(':========STEP 2=========:')

		# def wide_to_long(df):
		# 		# this function collapses a MultiIndex from 'wide' format to 'long' format

		# 		# The stack() function is used to "compress" a level in the DataFrame's columns.
		# 		# This transforms the DataFrame from a wide format to a long format.
		# 		# The reset_index() function is then used to reset the index of the DataFrame.
		# 		# This results in a DataFrame where each row represents a single observation for a symbol at a given time.
		# 		# The rename() function is used to rename the 'level_2' column to 'symbol'.
		# 		df = df.stack(level=0).reset_index().rename(columns={'level_2': 'symbol'})
		# 		return df

		# def add_year_interval(df):
		# 		# Set 'date', 'symbol', and 'interval' as indices
		# 		df.set_index(['date', 'symbol', 'interval'], inplace=True)

		# 		# Define the aggregation dictionary for resampling
		# 		agg_dict = {'open': 'first', 'high': 'max', 'low': 'min', 'close': 'last', 'volume':'sum'}

		# 		# Group the DataFrame by 'symbol' and 'interval' indices, filter for 1-month intervals, and resample to 1-year intervals
		# 		df_yearly = df[df.index.get_level_values('interval') == '1mo'].groupby(level=['symbol', 'interval']).resample('Y', level='date').agg(agg_dict)

		# 		# Reset the index of the DataFrame
		# 		df_yearly.reset_index(inplace=True)

		# 		# Add the 'interval' column back to the DataFrame
		# 		df_yearly['interval'] = '1y'
				
		# 		# Reset the index of the original DataFrame
		# 		df.reset_index(inplace=True)

		# 		# Concatenate the original DataFrame and the resampled DataFrame
		# 		df = pd.concat([df, df_yearly])

		# 		return df 

		# def tail_by_group(df):
		# 	df = df.groupby(['symbol', 'interval']).apply(lambda x: x.tail(5)).reset_index(drop=True)

		# 	return df

		# dataframes = wide_to_long(dataframes)
		# dataframes = add_year_interval(dataframes)
		# dataframes = tail_by_group(dataframes)
		# dataframes = categorize_interval_and_sort_data(dataframes)


		# save_to_html_and_open(dataframes)
		# threebp_df = threebp_main(dataframes)
		# save_to_html_and_open(threebp_df)
		# upload_to_gsheets(threebp_df)
		# # call_apps_script()








# ------------------------------------------------------------
		# works! 5min intra-day data
		# while True:
		# now = datetime.datetime.now()
		# seconds_until_next_5_minutes = 300 - (now.minute * 60 + now.second) % 300
		# print('seconds_until_next_5_minutes', seconds_until_next_5_minutes)

		# start_time = now.replace(second=0, microsecond=0)
		# end_time = start_time + timedelta(minutes=5)
		# intervals_daily = {
		# 		'5m': {
		# 				'start': start_time,
		# 				'end': end_time
		# 		}
		# }
		# print('--------start', intervals_daily["5m"]['start'])
		# print('--------end', intervals_daily["5m"]['end'])
		# time.sleep(seconds_until_next_5_minutes)

		# if now.weekday() < 6 and ((now.hour == 9 and now.minute >= 31) or (10 <= now.hour < 16) or (now.hour == 16 and now.minute <= 1)):
		
# ------------------------------------------------------------
		# works! 5min intra-day data
		# while True:
		# 		now = datetime.timedelta.now()
		# 		seconds_until_next_5_minutes = 300 - (now.minute * 60 + now.second) % 300  # Change 300 to 302 here
		# 		# Pause execution until the start of the next 5-minute mark
		# 		print('seconds_until_next_5_minutes', seconds_until_next_5_minutes)
		# 		time.sleep(seconds_until_next_5_minutes)  

		# 		# Delay the function call by a few seconds to give the data source time to update
		

		# 		# Update 'now' after the sleep period
		# 		now = datetime.datetime.now()  
		# 		intervals_daily = {
		# 				'5m': {
		# 						'start': datetime.datetime(now.year, now.month, now.day, now.hour, now.minute-5),
		# 						'end': datetime.datetime(now.year, now.month, now.day, now.hour, now.minute)
		# 				}
		# 		}
		# 		print('--------start', intervals_daily["5m"]['start'])
		# 		print('--------end', intervals_daily["5m"]['end'])

		# 		# Mon-Fri 9:31AM - 4:01PM
		# 		if now.weekday() < 5 and ((now.hour == 9 and now.minute >= 31) or (10 <= now.hour < 16) or (now.hour == 16 and now.minute <= 1)):
		# 				dataframes = Data.download_ohlcv(list1, intervals_daily, market_hours=True)
		# 				save_to_html_and_open(dataframes)



# ------------------------------------------------------------
		# works! 1min intra-day data
		# while True:
		# 		# Update 'now' and calculate the number of seconds until the next minute
		# 		now = datetime.datetime.now()
		# 		seconds_until_next_minute = 62 - now.second
		# 		time.sleep(seconds_until_next_minute)  # Pause execution until the start of the next minute

		# 		now = datetime.datetime.now()  # Update 'now' after the sleep period
		# 		intervals_daily = {
		# 				'1m': {
		# 						'start': datetime.datetime(now.year, now.month, now.day, now.hour, now.minute-1),
		# 						'end': datetime.datetime(now.year, now.month, now.day, now.hour, now.minute)
		# 				}
		# 		}

		# 		# Mon-Fri 9:31AM - 4:01PM
		# 		if now.weekday() < 5 and ((now.hour == 9 and now.minute >= 31) or (10 <= now.hour < 16) or (now.hour == 16 and now.minute <= 1)):
		# 				dataframes = Data.download_ohlcv(list1, intervals_daily, market_hours=True)
		# 				save_to_html_and_open(dataframes)

# ------------------------------------------------------------
		# market closed
		# dataframes = Data.download_ohlcv(list1, intervals_initial, market_hours=False)
		# save_to_html_and_open(dataframes)
		# sunday_data = process_data(dataframes)
		# threebp_main(sunday_data)


		# Save to a pickle file
		# sunday_data.to_pickle('data.pkl')

		# # # # Load 'sunday data' from a pickle file
		# sunday_data = pd.read_pickle('data.pkl')
# ------------------------------------------------------------

		# # 1 min data from Monday-Friday
		# weekday_data = Data.download_ohlcv(list1, intervals_daily)
		# weekday_data = process_data(weekday_data)
		# # save_to_html_and_open(weekday_data)
		# # weekday_data = remove_first_row_each_symbol(weekday_data)

		# save_to_html_and_open(weekday_data)
		# # Use the 1-minute data to update all timeframes
		# df_all = update_timeframes(sunday_data, weekday_data)
		# save_to_html_and_open(df_all)

		# # Save the updated data back to the file
		# df_all.to_pickle('data.pkl')


		# # # threebp_main(df_all)
		# save_to_html_and_open(df_all)
		

		
if __name__ == "__main__":
    asyncio.run(main())


		