
from extract.main import extract
from extract.yfin import process_data
from load.google_sheets import upload_to_gsheets
from transform.main import transform
from load.main import load
import asyncio
from transform.threebp import save_to_html_and_open, threebp_main
from utilities import dict_to_dataframe, load_pickle_object, save_dataframe
# from config import sectors, industries, industry_equities
import time
from extract.data import Data
import pandas as pd
import datetime
from datetime import timedelta

# --------------------------------------------------------------------

async def main():
		# sectors, industries, industry_equities = await extract()
		# exchange = transform(sectors, industries, industry_equities)
		
		# save_pickle_object(exchange, 'exchange')

		# exchange = load_pickle_object('exchange')

		# for sector in exchange.sectors:
		# 	for industry in sector.industries:
		# 		for equity in industry.equities:
		# 			print(equity.symbol)
		# 			equity.df = equity.download_ohlcv()

		# for sector in exchange.sectors:
		# 	for industry in sector.industries:
		# 		for equity in industry.equities:
		# 				await load(equity, exchange)
		

		# Define the intervals for the initial data download and processing
		intervals_initial = {
				'1m': '5d',  # For 1-minute timeframe, retrieve 5 days
				'5m': '5d',  # For 5-minute timeframe, retrieve 5 days
				'60m': '5d',  # For 1-hour timeframe, retrieve 5 days
				'1d': '5d',  # For 1-day timeframe, retrieve 5 days
				'1wk': '1mo',  # For 1-week timeframe, retrieve 1 month
				'1mo': '3mo'  # For 1-month timeframe, retrieve 3 months
		}

		# TODO: perform check to see if any new industries are included inside of 
		# industries.json that are not within the 'sector_industry_name_mapping' inside of config.py
		#--------------------------------------------------------------------------------------------------
		# equities symbol
		list1 = [
			"GWO.TO",
			"MFC.TO",
			"SFC.TO",
			"POW.TO",
			"ELF.TO",
			"TSU.TO",
			"GLXY.TO",
			"BITF.TO",
			"SATO.V",
			"DEFI.NE",
			"NDA.V",
			"GS.NE",
			"DMGI.V",
			"HIVE.V",
			"CXI.TO",
			"HUT.TO",
			"DELX.V",
			"PNP.TO",
			"MNT.TO",
			"MNS.TO",
			"HODL.CN",
			"BITK.V",
			"XAU.TO",
			"CF.TO",
			"HOLD.NE",
			"BIGG.CN",
			"COIN.NE",
			"FRNT.V",
			"CBIT.V",
			"SPTZ.CN",
			"FFH.TO",
			"IFC.TO",
			"DFY.TO",
			"FN.TO",
			"MKP.TO",
			"FC.TO",
			"AI.TO",
			"ECN.TO",
			"TF.TO",
			"DLCG.TO",
			"EQB.TO",
			"VBNK.TO",
			"CWB.TO",
			"LB.TO",
			"JPM.NE",
			"CM.TO",
			"BOFA.NE",
			"CITI.NE",
			"NA.TO",
			"RY.TO",
			"BMO.TO",
			"TD.TO",
			"BNS.TO",
			"ETHC.NE",
			"MBAI.CN",
			"LFE.TO",
			"WED.V",
			"ONEX.TO",
			"LCS.TO",
			"OLY.TO",
			"AIVC.V",
			"BAM.TO",
			"STCK.TO",
			"BN.TO",
			"BBUC.TO",
			"FIH-U.TO",
			"URB.TO",
			"WI.V",
			"GCG.TO",
			"UNC.TO",
			"PHYS-U.TO",
			"IDK.CN",
			"AGF-B.TO",
			"PHYS.TO",
			"CIX.TO",
			"CYB.TO",
			"CEF.TO",
			"CEF-U.TO",
			"CGI.TO",
			"FAP.TO",
			"AD-UN.TO",
			"PSLV-U.TO",
			"PSLV.TO",
			"RBN-UN.TO",
			"FFN.TO",
			"EIT-UN.TO",
			"HFPC-U.TO",
			"CVG.TO",
			"SII.TO",
			"MSRE-UN.TO",
			"PRM.TO",
			"DF.TO",
			"IGM.TO",
			"MID-UN.TO",
			"BNK.TO",
			"DGS.TO",
			"PTI-UN.TO",
			"RS.TO",
			"AIM.TO",
			"CLP-UN.TO",
			"LBS.TO",
			"ENI-UN.TO",
			"GDV.TO",
			"PWI.TO",
			"DS.TO",
			"FTN.TO",
			"ENS.TO",
			"BGI-UN.TO",
			"FW.V",
			"MMP-UN.TO",
			"SBC.TO",
			"SPPP.TO",
			"BCBN.NE",
			"BK.TO",
			"TIE.V",
			"DFN.TO",
			"FSZ.TO",
			"PDV.TO",
			"TINY.V",
			"INC-UN.TO",
			"BVOF-B.CN",
			"TLP-UN.CN",
			"ELC.V",
			"XTD.TO",
			"RCG.TO",
			"LITT.V",
			"OSP.TO",
			"SOL.CN",
			"MLC.NE",
			"NETZ.NE",
			"TEAM.CN",
			"MONT.V",
			"PRL.TO",
			"GSY.TO",
			"EPF.V",
			"VISA.NE",
			"MA.NE",
			"PYPL.NE",
			"CHW.TO",
			"CRWN.TO",
			"ACD.TO",
					"AFCC-H.V",
			"IAG.TO",
			"BRK.NE",
			"SLF.TO",
			"BNRE.TO",
			"X.TO",
			"CVX.V",
			"TBL.TO",
			"FBF.V",
			"CNO.V",
			"VNP.TO",
			"ECO.TO",
			"NANO.TO",
			"NEO.TO",
			"HG.CN",
			"BOS.TO",
			"GMG.V",
			"FNDX.CN",
			"GGG.V",
			"SJ.TO",
			"GDL.TO",
			"ADN.TO",
			"WFG.TO",
			"IFP.TO",
			"CFP.TO",
			"KLX.V",
			"CAS.TO",
			"CCL-B.TO",
			"WPK.TO",
			"RPI-UN.TO",
			"SXP.TO",
			"NEXE.V",
			"IFX.V",
			"MX.TO",
			"CHE-UN.TO",
			"GRA.TO",
			"FAT.CN",
			"CSO.V",
			"CAD.V",
			"IFOS.V",
			"NTR.TO",
			"MGRO.V",
			"NPK.TO",
			"CN.V",
			"GMIN.V",
			"AZS.V",
			"GATO.TO",
			"GBU.V",
			"EMPS.CN",
			"ASTR.V",
			"CGG.TO",
			"MUX.TO",
			"BRVO.V",
			"SIL.TO",
			"PPTA.TO",
			"NAU.V",
			"MMG.V",
			"ABRA.V",
			"TFPM.TO",
			"RRI.V",
			"GSPR.V",
			"AUCU.CN",
			"VML.V",
			"ALEX.V",
			"AEMC.V",
			"SM.V",
			"TUO.V",
			"EMPR.V",
			"SNAG.V",
			"SSV.V",
			"VOXR.TO",
			"COMT.CN",
			"NEXU.CN",
			"DSLV.V",
			"BRC.V",
			"STRR.V",
			"EQTY.V",
			"NVRO.CN",
			"SCOT.V",
			"AMK.V",
			"BWCG.V",
			"PTM.TO",
			"DEF.V",
			"CKG.V",
			"SLVR.V",
			"NUAG.TO",
			"PEX.V",
			"SSVR.V",
			"SLS.TO",
			"TUF.V",
			"MRZ.V",
			"BBB.V",
			"MTA.V",
			"OCG.V",
			"SBMI.V",
			"ITR.V",
			"CLIC.V",
			"CAPT.V",
			"EDR.TO",
			"BME.V",
			"VIPR.V",
			"KDK.V",
			"GOT.V",
			"GGD.TO",
			"MAX.V",
			"PGLD.V",
			"WEX.V",
			"AWM.V",
			"TBX.V",
			"CFE.CN",
			"ARK.V",
			"WAM.V",
			"ARU.V",
			"ESAU.CN",
			"AUAG.CN",
			"WBE.V",
			"CFX.TO",
			"MSR.V",
			"MML.CN",
			"NCX.V",
			"ZNG.V",
			"SHOW.CN",
			"NGEX.V",
			"DMX.V",
			"COSA.V",
			"MON.V",
			"NILI.V",
			"ALLI.NE",
			"WMK.V",
			"CUR.V",
			"PJX.V",
			"GMA.V",
			"FOM.TO",
			"FAR.TO",
			"VBAM.CN",
			"LITS.NE",
			"SYH.V",
			"NIO.V",
			"STS.V",
			"BY.CN",
			"IVN.TO",
			"TIG.V",
			"FWZ.V",
			"JUGR.V",
			"CD.V",
			"SRG.V",
			"TECK-B.TO",
			"REG.V",
			"HERC.CN",
			"GLO.TO",
			"CVV.V",
			"MUN.V",
			"AFM.V",
			"MMA.V",
			"BATX.CN",
			"ALDE.V",
			"FPC.V",
			"ERKA.CN",
			"OIII.V",
			"ETG.TO",
			"PNPN.V",
			"STUD.V",
			"FIL.TO",
			"AAN.V",
			"FMC.V",
			"NOVR.V",
			"DBG.V",
			"EVNI.V",
			"NKG.V",
			"MDI.TO",
			"M.CN",
			"VOY.CN",
			"PMET.V",
			"GLAD.V",
			"LLG.V",
			"PGE.V",
			"TDG.V",
			"NVLH.CN",
			"UCU.V",
			"VZLA.V",
			"CXC.CN",
			"EMX.V",
			"DLP.V",
			"AAG.V",
			"NIM.V",
			"ESPN.V",
			"ETL.V",
			"BRO.V",
			"AKE.TO",
			"ALS.TO",
			"AGX.V",
			"CNRI.V",
			"RR.CN",
			"AZM.V",
			"PNRL.V",
			"FNI.CN",
			"GEO.TO",
			"WRN.TO",
			"OM.V",
			"CCE.V",
			"EMO.V",
			"SKE.TO",
			"DG.V",
			"LBNK.V",
			"PRYM.TO",
			"KLD.V",
			"LITH.V",
			"MD.V",
			"FLYN.V",
			"AJN.CN",
			"INTR.V",
			"PGX.V",
			"SME.V",
			"NWX.V",
			"SMD.V",
			"GQC.V",
			"HZ.CN",
			"MKR.V",
			"MOLY.NE",
			"PML.V",
			"LTH.V",
			"BULL.CN",
			"HPQ.V",
			"ARS.CN",
			"CNC.V",
			"TOC.CN",
			"HAR.V",
			"PRR.CN",
			"MKA.V",
			"EMM.V",
			"DEC.V",
			"NKL.V",
			"QTWO.V",
			"CVW.V",
			"SDCU.V",
			"FOX.CN",
			"BMR.V",
			"STGX.CN",
			"ULTH.CN",
			"LEXI.V",
			"HUNT.CN",
			"TWR.V",
			"PWM.V",
			"SGML.V",
			"CC.CN",
			"RMR.V",
			"CPAU.V",
			"CPS.V",
			"NOAL.V",
			"BKM.V",
			"LEM.V",
			"CUSN.V",
			"NWST.V",
			"MAXX.CN",
			"NRM.V",
			"MMS.V",
			"LIM.CN",
			"GIGA.V",
			"LIT.V",
			"ECOR.TO",
			"BEX.V",
			"TAU.V",
			"GPH.V",
			"PEGA.V",
			"NVLI.CN",
			"PNRG.CN",
			"ELEC.V",
			"LRA.V",
			"CDB.V",
			"WHY.V",
			"CNX.V",
			"EPL.V",
			"LUCA.V",
			"BOLT.CN",
			"DEFN.V",
			"FPX.V",
			"TN.CN",
			"LIS.V",
			"VRTX.CN",
			"SLV.CN",
			"EDM.V",
			"SRS.CN",
			"FCLI.V",
			"FIN.V",
			"RCK.V",
			"VLT.V",
			"APN.V",
			"LIRC.TO",
			"ATOM.V",
			"UUSA.CN",
			"NOU.V",
			"MLP.V",
			"AMC.TO",
			"SCZ.V",
			"TMAS.CN",
			"BZ.V",
			"STU.V",
			"AZT.V",
			"NICU.V",
			"HAN.V",
			"SLI.V",
			"WML.V",
			"XRI.CN",
			"STE.V",
			"CDN.CN",
			"DAN.V",
			"PLAN.V",
			"EMNT.V",
			"LR.V",
			"ATY.V",
			"PHOS.CN",
			"AMPS.CN",
			"GEL.V",
			"USCM.CN",
			"CCC.CN",
			"LCE.V",
			"GDIG.CN",
			"ADZN.V",
			"ION.V",
			"LI.V",
			"KC.V",
			"GRAT.V",
			"PE.V",
			"TRAC.CN",
			"VUL.V",
			"LIFT.V",
			"NEXT.TO",
			"SRA.V",
			"UDI.CN",
			"QREE.CN",
			"ABR.V",
			"REX.V",
			"FMS.V",
			"OCO.V",
			"PGZ.V",
			"AMY.V",
			"PRIZ.CN",
			"ESK.V",
			"TCEC.CN",
			"NGC.V",
			"RFLX.CN",
			"TORQ.V",
			"IMCX.CN",
			"NB.TO",
			"LGO.TO",
			"SX.CN",
			"SALT.V",
			"JZR.V",
			"IBAT.CN",
			"LAC.TO",
			"CRE.V",
			"FL.V",
			"EBR.CN",
			"EDDY.V",
			"TCO.V",
			"EMN.V",
			"FE.CN",
			"QBAT.CN",
			"HECO.CN",
			"SAGE.V",
			"AWLI.CN",
			"WEST.CN",
			"MEGA.CN",
			"POWR.CN",
			"PM.CN",
			"ELBM.V",
			"EPR.CN",
			"ALCU.CN",
			"TEX.CN",
			"AMQ.CN",
			"TROY.CN",
			"RML.V",
			"TBK.V",
			"RSM.V",
			"HMR.V",
			"GRZ.V",
			"NPR.V",
			"VSR.V",
			"SOMA.V",
			"SIG.CN",
			"MKO.V",
			"IGO.V",
			"AMRQ.V",
			"MMY.V",
			"MFG.V",
			"NGD.TO",
			"ELD.TO",
			"RGC.V",
			"BNN.CN",
			"K.TO",
			"SGD.V",
			"DPM.TO",
			"DNG.TO",
			"ARTG.V",
			"FDR.V",
			"AGI.TO",
			"CBR.V",
			"GPAC.V",
			"OSI.V",
			"CXB.TO",
			"LUG.TO",
			"WG.CN",
			"RISE.CN",
			"WPM.TO",
			"OGN.V",
			"ARIS.TO",
			"EQX.TO",
			"CG.TO",
			"VIO.V",
			"FVI.TO",
			"WDO.TO",
			"OR.TO",
			"FISH.V",
			"KRR.TO",
			"RIO.V",
			"JKS.CN",
			"AEM.TO",
			"IMG.TO",
			"VGD.V",
			"MAU.V",
			"SEA.TO",
			"ORA.TO",
			"RDS.V",
			"CGC.V",
			"CNL.TO",
			"ASE.CN",
			"BAU.V",
			"ABX.TO",
			"BRW.V",
			"EDV.TO",
			"ECR.V",
			"CEE.TO",
			"GPG.V",
			"AE.V",
			"PAAS.TO",
			"LIO.V",
			"SUP.V",
			"OGC.TO",
			"RGD.V",
			"WVM.V",
			"RUSH.V",
			"PRB.TO",
			"SSL.TO",
			"PMC.CN",
			"TEM.V",
			"GOLD.TO",
			"RPX.V",
			"GFG.V",
			"VGCX.TO",
			"ELE.V",
			"NGT.TO",
			"BTO.TO",
			"PRU.TO",
			"THX.V",
			"GTWO.V",
			"SPA.V",
			"KRI.V",
			"RBX.V",
			"JAG.TO",
			"VG.V",
			"AU.V",
			"TXG.TO",
			"KNT.TO",
			"NFG.V",
			"BYN.V",
			"USGD.CN",
			"RUP.TO",
			"HSTR.V",
			"ATX.V",
			"DYG.V",
			"GMV.V",
			"FOR.V",
			"VAU.V",
			"LUM.V",
			"NGE.V",
			"FNV.TO",
			"WGO.V",
			"PA.V",
			"AMX.V",
			"MAI.V",
			"OSK.TO",
			"LME.V",
			"LORD.V",
			"HARD.CN",
			"QIM.CN",
			"GSTM.V",
			"OLA.TO",
			"MGG.V",
			"PALI.V",
			"INCA.V",
			"DLTA.V",
			"HWG.CN",
			"FMAN.V",
			"BTR.V",
			"ELVT.V",
			"PUMA.V",
			"SSRM.TO",
			"GGO.V",
			"WRLG.V",
			"GLDL.V",
			"NCAU.V",
			"CERT.V",
			"ARIC.V",
			"TUD.V",
			"DEX.V",
			"NCLR.CN",
			"IAU.TO",
			"AUEN.V",
			"GXX.V",
			"AUAU.V",
			"WHN.V",
			"TIN.V",
			"NINE.CN",
			"LAB.V",
			"ROS.V",
			"ODV.V",
			"GUS.V",
			"LGC.V",
			"TECT.V",
			"ALTA.V",
			"NG.TO",
			"EDG.V",
			"MND.TO",
			"ELO.TO",
			"RVG.V",
			"MLM.NE",
			"GAL.V",
			"BLLG.CN",
			"RDU.V",
			"GSHR.V",
			"GLDC.V",
			"IRV.CN",
			"BLDS.V",
			"FNAU.CN",
			"LVX.V",
			"GXS.V",
			"PHNM.V",
			"GMR.CN",
			"GWM.V",
			"HIGH.V",
			"ABM.V",
			"GRHK.CN",
			"WRR.V",
			"GG.V",
			"GBRC.V",
			"XIM.V",
			"NOM.CN",
			"GSRI.CN",
			"SUI.V",
			"DCLI.CN",
			"AAU.V",
			"RAK.V",
			"BSR.V",
			"RDG.V",
			"SF.CN",
			"GTCH.CN",
			"OPHR.V",
			"PATH.CN",
			"AGC.CN",
			"NFLD.CN",
			"BCM.V",
			"RAGE.V",
			"ELEM.CN",
			"BIG.V",
			"AYA.TO",
			"SVM.TO",
			"DV.V",
			"RSMX.V",
			"APGO.V",
			"FR.TO",
			"SVRS.V",
			"MAG.TO",
			"RSLV.V",
			"SVE.V",
			"KTN.V",
			"GSVR.V",
			"EML.V",
			"IPT.V",
			"APM.V",
			"BNKR.V",
			"KUYA.CN",
			"AGMR.V",
			"ZAC.V",
			"TM.V",
			"CS.TO",
			"LUN.TO",
			"III.TO",
			"HBM.TO",
			"ERO.TO",
			"TKO.TO",
			"ARG.TO",
			"MARI.TO",
			"ASCU.TO",
			"CUU.V",
			"ECU.V",
			"HCH.V",
			"QCCU.V",
			"IE.TO",
			"LA.V",
			"BCU.V",
			"DCMC.V",
			"FM.TO",
			"SLMN.V",
			"TWO.V",
			"VCU.V",
			"CTH.V",
			"SGQ.V",
			"MOX.V",
			"U-U.TO",
			"CCO.TO",
			"U-UN.TO",
			"EU.V",
			"NXE.TO",
			"DML.TO",
			"FCU.TO",
			"FUU.V",
			"CAKE.CN",
			"URE.TO",
			"WUC.CN",
			"URC.TO",
			"ISO.V",
			"EFR.TO",
			"SUU.V",
			"GREN.CN",
			"FIND.V",
			"API.CN",
			"SASK.CN",
			"LUR.CN",
			"GXU.V",
			"TMC.V",
			"IMO.TO",
			"SU.TO",
			"XOM.NE",
			"CHEV.NE",
			"CVE.TO",
			"SHLE.TO",
			"MCB.TO",
			"TVK.TO",
			"NOA.TO",
			"CEU.TO",
			"PSD.TO",
			"TCW.TO",
			"PSI.TO",
			"MATR.TO",
			"TOT.TO",
			"STEP.TO",
			"EFX.TO",
			"HWO.TO",
			"CFW.TO",
			"PHX.TO",
			"WRG.TO",
			"PD.TO",
			"SDI.V",
			"ESI.TO",
			"PKI.TO",
			"GIII.V",
			"NSE.V",
			"CDR.TO",
			"SEI.V",
			"HHRS.TO",
			"TNZ.TO",
			"ATH.TO",
			"WOGC.CN",
			"FO.V",
			"VLE.TO",
			"MEG.TO",
			"PXT.TO",
			"AXL.V",
			"CNQ.TO",
			"LOU.V",
			"KEL.TO",
			"PSK.TO",
			"ARX.TO",
			"IPCO.TO",
			"HWX.TO",
			"HME.V",
			"OBE.TO",
			"RBY.TO",
			"KEI.TO",
			"CDA.V",
			"CPG.TO",
			"SOIL.TO",
			"CEI.V",
			"PEY.TO",
			"ORC-B.V",
			"OVV.TO",
			"POU.TO",
			"AOI.TO",
			"NVA.TO",
			"PNE.TO",
			"ERF.TO",
			"GTE.TO",
			"WCP.TO",
			"FRU.TO",
			"HEVI.V",
			"KEC.TO",
			"AAV.TO",
			"TOU.TO",
			"CJ.TO",
			"ALV.V",
			"GASX.V",
			"FEC.TO",
			"AVN.V",
			"BNE.TO",
			"IPO.TO",
			"LCX.V",
			"BTE.TO",
			"TPL.V",
			"CR.TO",
			"VET.TO",
			"VUX.V",
			"SGY.TO",
			"ROK.V",
			"TVE.TO",
			"TAO.V",
			"RHC.V",
			"JOY.TO",
			"AFE.V",
			"RECO.V",
			"PRQ.TO",
			"BIR.TO",
			"CNE.TO",
			"JEV.V",
			"HAM.V",
			"EOG.V",
			"SDE.TO",
			"CEC.V",
			"WIL.V",
			"YGR.TO",
			"TPC.V",
			"CEQ.V",
			"OYL.V",
			"MCF.V",
			"SOU.V",
			"TOH.V",
			"OIL.CN",
			"DME.V",
			"RZE.V",
			"TCF.CN",
			"ALA.TO",
			"KEY.TO",
			"SRR.V",
			"PPL.TO",
			"TRP.TO",
			"ENB.TO",
			"GEI.TO",
			"TPZ.TO",
			"MUSH.V",
			"PRMW.TO",
			"COLA.NE",
			"GURU.TO",
			"YERB-U.V",
			"JSDA.CN",
			"HILL.V",
			"OPTI.CN",
			"PEAS.V",
			"HBFG.CN",
			"SWP.TO",
			"PBH.TO",
			"MFI.TO",
			"JWEL.TO",
			"SAP.TO",
			"HLF.TO",
			"BHSC.CN",
			"FRSH.V",
			"BOIL.CN",
			"SOY.TO",
			"PNGA.CN",
			"MOOO.CN",
			"MEAT.CN",
			"NGRB.NE",
			"BITE.CN",
			"GFCO.CN",
			"DWS.V",
			"RSI.TO",
			"TYUM.CN",
			"GRAM.NE",
			"TAAT.CN",
			"NWC.TO",
			"L.TO",
			"WN.TO",
			"MRU.TO",
			"PG.NE",
			"KPT.TO",
			"CGII.CN",
			"GCL.TO",
			"CRP.TO",
			"OGO.V",
			"SES.TO",
			"VCI.V",
			"GFL.TO",
			"WCN.TO",
			"EWK.V",
			"VTX.V",
			"YES.V",
			"BLM.V",
			"LUX.CN",
			"ROOF.V",
			"ECM.V",
			"DCM.TO",
			"KBL.TO",
			"TRI.TO",
			"RBA.TO",
			"DXT.TO",
			"ISV.TO",
			"CGY.TO",
			"GDI.TO",
			"KUT.V",
			"DE.V",
			"BBU-UN.TO",
			"HON.NE",
			"DIV.TO",
			"CHR.TO",
			"AC.TO",
			"EIF.TO",
			"JET-B.NE",
			"JET.NE",
			"CJET.NE",
			"GSI.V",
			"ZDC.V",
			"XX.V",
			"SECU.V",
			"SCAN.V",
			"TMG.V",
			"ACT.CN",
			"BRM.V",
			"SHRC.CN",
			"DST.CN",
			"QST.V",
			"DESG.NE",
			"PNG.V",
			"NSCI.V",
			"ASTL.TO",
			"CIA.TO",
			"STLC.TO",
			"LIF.TO",
			"TSL.TO",
			"EXRO.TO",
			"LPS.V",
			"ZAIR.CN",
			"FTG.TO",
			"MDA.TO",
			"BA.NE",
			"HRX.TO",
			"CAE.TO",
			"MAL.TO",
			"BBD-B.TO",
			"AZ.V",
			"FLY.V",
			"MAXQ.NE",
			"DPRO.CN",
			"VOL.V",
			"KWE.V",
			"MRE.TO",
			"XTC.TO",
			"MG.TO",
			"LNR.TO",
			"WPRT.TO",
			"HC.NE",
			"ATS.TO",
			"SIS.TO",
			"TLA.V",
			"VLN.TO",
			"ENW.V",
			"BLDP.TO",
			"NXH.V",
			"LGT-B.TO",
			"WTE.TO",
			"ALC.TO",
			"RUS.TO",
			"DBM.TO",
			"WJX.TO",
			"TIH.TO",
			"FTT.TO",
			"ADEN.TO",
			"CNR.TO",
			"CP.TO",
			"BDT.TO",
			"ATRL.TO",
			"BDGI.TO",
			"STN.TO",
			"ARE.TO",
			"WSP.TO",
			"CJT.TO",
			"TTNM.TO",
			"UPS.NE",
			"AND.TO",
			"PDO.CN",
			"BDI.TO",
			"EFN.TO",
			"DRX.TO",
			"CYM.V",
			"IVX.V",
			"TFII.TO",
			"MTL.TO",
			"AEP.V",
			"BUI.TO",
			"AFN.TO",
			"TGH.V",
			"LEV.TO",
			"GPV.V",
			"VSOL.NE",
			"HEO.TO",
			"PRME.CN",
			"H.TO",
			"FTS.TO",
			"EMA.TO",
			"CUP-U.TO",
			"CU-X.TO",
			"ACO-Y.TO",
			"ACO-X.TO",
			"CU.TO",
			"BIP-UN.TO",
			"MXG.TO",
			"TA.TO",
			"CPX.TO",
			"WEB.V",
			"SUNN.CN",
			"BEP-UN.TO",
			"BEPC.TO",
			"PIF.TO",
			"BLX.TO",
			"ARR.TO",
			"AQN.TO",
			"RE.V",
			"GIP.V",
			"NPI.TO",
			"LCFS.TO",
			"GRB.V",
			"UGE.V",
			"REVV.V",
			"INE.TO",
			"MOVE.NE",
			"SPB.TO",
			"EVGN.V",
			"BIPC.TO",
			"SEV.V",
			"CLS.TO",
			"ZTE.CN",
			"HEAT.CN",
			"WIFI.CN",
			"NVDA.NE",
			"AMD.NE",
			"INTC.NE",
			"MRM.CN",
			"PTK.V",
			"MSFT.NE",
			"NVEI.TO",
			"TOI.V",
			"CVO.TO",
			"CPLF.TO",
			"MDF.TO",
			"HAI.TO",
			"MOGO.TO",
			"PAY.TO",
			"BB.TO",
			"SCPE.CN",
			"TC.TO",
			"VERS.NE",
			"STC.TO",
			"PLUG.CN",
			"NOW.V",
			"BTQ.NE",
			"MIM.V",
			"CTRL.V",
			"BYND.CN",
			"RAIL.CN",
			"TIXT.TO",
			"NFTX.NE",
			"BVCI.CN",
			"CLIP.V",
			"FOBI.V",
			"PKK.CN",
			"NBVA.V",
			"CYBT.CN",
			"VRAI.CN",
			"UAV.CN",
			"FLT.V",
			"RDRS.CN",
			"THNC.TO",
			"UBER.NE",
			"QFOR.TO",
			"CRM.NE",
			"IQ.V",
			"BLN.TO",
			"SHOP.TO",
			"CMG.TO",
			"CSU.TO",
			"URL.CN",
			"OSS.V",
			"DCBO.TO",
			"LMN.V",
			"REAL.TO",
			"CTZ.V",
			"ABXX.NE",
			"OTEX.TO",
			"TCXT.V",
			"DTOL.TO",
			"LSPD.TO",
			"DSG.TO",
			"MVP.TO",
			"TCS.TO",
			"SYZ.TO",
			"ENGH.TO",
			"DND.TO",
			"CDAY.TO",
			"INSP.V",
			"RSS.V",
			"RIWI.V",
			"KXS.TO",
			"DGHI.V",
			"INX.V",
			"INXD.NE",
			"QIS.V",
			"MAPS.V",
			"LQWD.V",
			"IFSS.NE",
			"UI.V",
			"METG.CN",
			"WISH.V",
			"AXE.V",
			"WFLD.V",
			"MHUB.V",
			"VXTR.V",
			"BWLK.V",
			"ALY.V",
			"AICO.CN",
			"PLRB.V",
			"TWOH.CN",
			"ARWY.CN",
			"VSBY.CN",
			"IBM.NE",
			"CTS.TO",
			"SFTC.TO",
			"SPOT.V",
			"ALYA.TO",
			"PBIT.CN",
			"PVT.V",
			"KNR.NE",
			"QUIS.V",
			"FARM.V",
			"DCSI.CN",
			"UFC.V",
			"MRC.TO",
			"YEG.V",
			"BTB-UN.TO",
			"AP-UN.TO",
			"D-UN.TO",
			"INO-UN.TO",
			"TNT-UN.TO",
			"DIR-UN.TO",
			"GRT-UN.TO",
			"NXR-UN.TO",
			"PRV-UN.TO",
			"MRT-UN.TO",
			"CRR-UN.TO",
			"HR-UN.TO",
			"NET-UN.V",
			"MR-UN.TO",
			"AX-UN.TO",
			"MPCT-UN.TO",
			"PMZ-UN.TO",
			"CRT-UN.TO",
			"SRU-UN.TO",
			"CHP-UN.TO",
			"FCR-UN.TO",
			"REI-UN.TO",
			"PLZ-UN.TO",
			"FCD-UN.TO",
			"SGR-U.TO",
			"SGR-UN.TO",
			"BEI-UN.TO",
			"CAR-UN.TO",
			"MI-UN.TO",
			"KMP-UN.TO",
			"MHC-U.TO",
			"MHC-UN.TO",
			"IIP-UN.TO",
			"MAR-UN.V",
			"DRR-U.TO",
			"MRG-UN.TO",
			"HOM-UN.TO",
			"HOM-U.TO",
			"ERE-UN.TO",
			"CSH-UN.TO",
			"CIGI.TO",
			"FSV.TO",
			"MEQ.TO",
			"TCN.TO",
			"YAK.V",
			"SVI.TO",
			"BRE.TO",
			"AIF.TO",
			"PKT.V",
			"NXLV.V",
			"TRBE.V",
			"NWH-UN.TO",
			"APR-UN.TO",
			"WFC.TO",
			"GDC.TO",
			"MRD.TO",
			"DRM.TO",
			"MENE.V",
			"DII-B.TO",
			"RCH.TO",
			"TRZ.TO",
			"IFA.TO",
			"GIL.TO",
			"UNI.TO",
			"GOOS.TO",
			"ACQ.TO",
			"COST.NE",
			"DOL.TO",
			"PESO.V",
			"WMT.NE",
			"NFI.TO",
			"TSLA.NE",
			"VMC.V",
			"FHYD.V",
			"DOO.TO",
			"PBL.TO",
			"PMKR.V",
			"RVLY.V",
			"NKE.NE",
			"SHOE.CN",
			"TPX-B.TO",
			"BR.TO",
			"AMZN.NE",
			"NTAR.CN",
			"BYD.TO",
			"WOLF.V",
			"PLC.TO",
			"BRAG.TO",
			"GET.CN",
			"TIDL.CN",
			"VST.CN",
			"GAME.V",
			"CKI.TO",
			"KITS.TO",
			"ATD.TO",
			"ZZZ.TO",
			"LNF.TO",
			"CTC.TO",
			"GBT.TO",
			"PET.TO",
			"IDG.TO",
			"AMB.CN",
			"RET.V",
			"ROOT.TO",
			"ATZ.TO",
			"HD.NE",
			"AAPL.NE",
			"QSR.TO",
			"MCDS.NE",
			"PZA.TO",
			"SRV-UN.TO",
			"BPF-UN.TO",
			"SBUX.NE",
			"MTY.TO",
			"AW-UN.TO",
			"KEG-UN.TO",
			"COHO.V",
			"ODD.V",
			"GH.TO",
			"NFLX.NE",
			"DIS.NE",
			"CGX.TO",
			"TBRD.V",
			"NTE.V",
			"OAM.V",
			"BRMI.TO",
			"WILD.TO",
			"AMEN.NE",
			"TOY.TO",
			"TWC.TO",
			"READ.CN",
			"Y.TO",
			"ILLM.TO",
			"EQ.V",
			"META.NE",
			"BILD.V",
			"GOOG.NE",
			"FORA.TO",
			"APLV.CN",
			"SBIO.V",
			"QBR-B.TO",
			"VZ.NE",
			"RCI-B.TO",
			"CGO.TO",
			"T.TO",
			"BCE.TO",
			"CCA.TO",
			"TGO.TO",
			"TVA-B.TO",
			"TTZ.V",
			"QTRH.TO",
			"BEW.V",
			"ET.TO",
			"TSAT.TO",
			"CSCO.NE",
			"VCM.TO",
			"CMI.V",
			"MMAX.CN",
			"NUR.CN",
			"HITI.V",
			"LOTA.CN",
			"NBLY.TO",
			"IWIN.CN",
			"OPS.TO",
			"BLCO.TO",
			"OTC.V",
			"ZEN.V",
			"GRIN.CN",
			"CANB.V",
			"CPH.TO",
			"DHT-UN.TO",
			"MPH.V",
			"RX.V",
			"DB.V",
			"VEXT.CN",
			"FH.NE",
			"GUD.TO",
			"EPIC.CN",
			"CRDL.TO",
			"GTII.CN",
			"HUGE.CN",
			"LOVE.V",
			"VRNO.NE",
			"INNO.CN",
			"BHC.TO",
			"CRON.TO",
			"CXXI.CN",
			"GDNS.CN",
			"SBBC.V",
			"TIUM-U.CN",
			"BNXT.CN",
			"MDP.TO",
			"TLRY.TO",
			"AAWH-U.CN",
			"ROMJ.V",
			"LSL.V",
			"TRUL.CN",
			"CDVA.CN",
			"PCLO.V",
			"OGI.TO",
			"XTRX.CN",
			"PLTH.CN",
			"MRMD.CN",
			"CL.CN",
			"RIV.CN",
			"SHWZ.NE",
			"HLS.TO",
			"BZAM.CN",
			"GWAY.CN",
			"JUSH.CN",
			"LOWL.CN",
			"MYCO.CN",
			"FFNT.CN",
			"IMCC.CN",
			"PBF.CN",
			"ACRG-B-U.CN",
			"TRUE.CN",
			"VHI.TO",
			"ADK.V",
			"KSI.TO",
			"CDX.V",
			"AIAI.CN",
			"NURS.V",
			"RHT.V",
			"THNK.V",
			"UDOC.CN",
			"TMED.CN",
			"XYBN.V",
			"NDAT.CN",
			"BUX.CN",
			"SONA.CN",
			"AVCR.V",
			"TELO.V",
			"IZO.CN",
			"VMD.TO",
			"ASG.V",
			"QIPT.TO",
			"HTL.TO",
			"VPT.V",
			"NGMD.V",
			"PINK.V",
			"TLT.V",
			"BLO.CN",
			"SGMD.V",
			"IBT.V",
			"TTI.V",
			"EPRX.TO",
			"MIR.V",
			"FRX.TO",
			"MSCL.V",
			"MDMA.CN",
			"MMED.NE",
			"ACOG.CN",
			"GLAB.CN",
			"NGEN.V",
			"PHRM.CN",
			"TELI.CN",
			"DTC.CN",
			"SBM.V",
			"CYBN.NE",
			"DOSE.CN",
			"BCT.TO",
			"ONC.TO",
			"COOL.CN",
			"AEZS.TO",
			"ARCH.V",
			"XRTX.V",
			"COV.V",
			"BMND.NE",
			"DRUG.CN",
			"CZO.V",
			"AWKN.NE",
			"ASEP.CN",
			"TH.TO",
			"APS.TO",
			"CMND.CN",
			"ABBV.NE",
			"PFE.NE",
			"UNH.NE",
			"CVS.NE",
			"KDA.V",
			"NPTH.V",
			"WELL.TO",
			"EXE.TO",
			"DR.TO",
			"SIA.TO",
			"NLH.V",
			"DNTL.TO",
			"PHA.V",
			"CRRX.TO"
]
		# list1 = ["GWO.TO", "MFC.TO", "SHOP.TO", "TLRY.TO", "BIGG.CN"]
		list1 = ["BTC-USD", "ETH-USD"]


# ------------------------------------------------------------
		# works! 5min intra-day data
# while True:
		now = datetime.datetime.now()
		seconds_until_next_5_minutes = 300 - (now.minute * 60 + now.second) % 300
		print('seconds_until_next_5_minutes', seconds_until_next_5_minutes)

		start_time = now.replace(second=0, microsecond=0)
		end_time = start_time + timedelta(minutes=5)
		intervals_daily = {
				'5m': {
						'start': start_time,
						'end': end_time
				}
		}
		print('--------start', intervals_daily["5m"]['start'])
		print('--------end', intervals_daily["5m"]['end'])
		# time.sleep(seconds_until_next_5_minutes)

		# if now.weekday() < 6 and ((now.hour == 9 and now.minute >= 31) or (10 <= now.hour < 16) or (now.hour == 16 and now.minute <= 1)):
		print('=================: 1')
		dataframes = Data.download_ohlcv(list1, intervals_initial, market_hours=False)
		print('=================: 2')
		dataframes = process_data(dataframes)
                
		save_to_html_and_open(dataframes)
		print('=================: 3')
		threebp_df = threebp_main(dataframes)
		save_to_html_and_open(threebp_df)
		upload_to_gsheets(threebp_df)









# ------------------------------------------------------------
		# works! 5min intra-day data
		# while True:
		# 		now = datetime.timedelta.now()
		# 		seconds_until_next_5_minutes = 300 - (now.minute * 60 + now.second) % 300  # Change 300 to 302 here
		# 		# Pause execution until the start of the next 5-minute mark
		# 		print('seconds_until_next_5_minutes', seconds_until_next_5_minutes)
		# 		time.sleep(seconds_until_next_5_minutes)  

		# 		# Delay the function call by a few seconds to give the data source time to update
		

		# 		# Update 'now' after the sleep period
		# 		now = datetime.datetime.now()  
		# 		intervals_daily = {
		# 				'5m': {
		# 						'start': datetime.datetime(now.year, now.month, now.day, now.hour, now.minute-5),
		# 						'end': datetime.datetime(now.year, now.month, now.day, now.hour, now.minute)
		# 				}
		# 		}
		# 		print('--------start', intervals_daily["5m"]['start'])
		# 		print('--------end', intervals_daily["5m"]['end'])

		# 		# Mon-Fri 9:31AM - 4:01PM
		# 		if now.weekday() < 5 and ((now.hour == 9 and now.minute >= 31) or (10 <= now.hour < 16) or (now.hour == 16 and now.minute <= 1)):
		# 				dataframes = Data.download_ohlcv(list1, intervals_daily, market_hours=True)
		# 				save_to_html_and_open(dataframes)



# ------------------------------------------------------------
		# works! 1min intra-day data
		# while True:
		# 		# Update 'now' and calculate the number of seconds until the next minute
		# 		now = datetime.datetime.now()
		# 		seconds_until_next_minute = 62 - now.second
		# 		time.sleep(seconds_until_next_minute)  # Pause execution until the start of the next minute

		# 		now = datetime.datetime.now()  # Update 'now' after the sleep period
		# 		intervals_daily = {
		# 				'1m': {
		# 						'start': datetime.datetime(now.year, now.month, now.day, now.hour, now.minute-1),
		# 						'end': datetime.datetime(now.year, now.month, now.day, now.hour, now.minute)
		# 				}
		# 		}

		# 		# Mon-Fri 9:31AM - 4:01PM
		# 		if now.weekday() < 5 and ((now.hour == 9 and now.minute >= 31) or (10 <= now.hour < 16) or (now.hour == 16 and now.minute <= 1)):
		# 				dataframes = Data.download_ohlcv(list1, intervals_daily, market_hours=True)
		# 				save_to_html_and_open(dataframes)

# ------------------------------------------------------------
		# market closed
		# dataframes = Data.download_ohlcv(list1, intervals_initial, market_hours=False)
		# save_to_html_and_open(dataframes)
		# sunday_data = process_data(dataframes)
		# threebp_main(sunday_data)


		# Save to a pickle file
		# sunday_data.to_pickle('data.pkl')

		# # # # Load 'sunday data' from a pickle file
		# sunday_data = pd.read_pickle('data.pkl')
# ------------------------------------------------------------

		# # 1 min data from Monday-Friday
		# weekday_data = Data.download_ohlcv(list1, intervals_daily)
		# weekday_data = process_data(weekday_data)
		# # save_to_html_and_open(weekday_data)
		# # weekday_data = remove_first_row_each_symbol(weekday_data)

		# save_to_html_and_open(weekday_data)
		# # Use the 1-minute data to update all timeframes
		# df_all = update_timeframes(sunday_data, weekday_data)
		# save_to_html_and_open(df_all)

		# # Save the updated data back to the file
		# df_all.to_pickle('data.pkl')


		# # # threebp_main(df_all)
		# save_to_html_and_open(df_all)
		

		
if __name__ == "__main__":
    asyncio.run(main())


		